# Tasca S12.01. APIs REST

Aplicaràs el que has après sobre APIs REST, mètodes HTTP i codis d'estat, utilitzant APIs públiques per consultar dades, filtrar-les i finalment desar-les en un DataFrame de pandas.

**Recursos**:

- Nivell 1:  
[{JSON} Placeholder](https://jsonplaceholder.typicode.com/)

- Nivell 2:  
[Try Public APIs for free](https://github.com/public-apis/public-apis)

- Nivell 3:  
[Open Data BCN](https://opendata-ajuntament.barcelona.cat/ca/desenvolupadors#APIS)

## Importa llibreries

In [1]:
import requests
from requests.exceptions import HTTPError
import pprint as pp
import pandas as pd

## Nivell 1

Des d’un Jupyter Notebook faràs els següents exercicis utilitzant la llibreria requests de Python.

**Exploració bàsica amb una API de laboratori.**

### 1. Consulta l’API pública [JSONPlaceholder](https://jsonplaceholder.typicode.com/) utilitzant el mètode GET per obtenir:

- Llista de publicacions (/posts)
- Llista d’usuaris (/users)
- Llista de tasques (/todos)

In [2]:
BASE_URL = "https://jsonplaceholder.typicode.com"

def get_results(endpoint: str):
    try:
        response = requests.get(f"{BASE_URL}/{endpoint}")
        response.raise_for_status()
        return response.json(), response.status_code
    except HTTPError as http_err:
        print(f"HTTP error for {endpoint}: {http_err}")
    except Exception as err:
        print(f"Other error for {endpoint}: {err}")
    return None

In [3]:
posts, posts_status = get_results("posts")
users, users_status = get_results("users")
todos, todos_status = get_results("todos")

In [4]:
pp.pprint(posts)

[{'body': 'quia et suscipit\n'
          'suscipit recusandae consequuntur expedita et cum\n'
          'reprehenderit molestiae ut ut quas totam\n'
          'nostrum rerum est autem sunt rem eveniet architecto',
  'id': 1,
  'title': 'sunt aut facere repellat provident occaecati excepturi optio '
           'reprehenderit',
  'userId': 1},
 {'body': 'est rerum tempore vitae\n'
          'sequi sint nihil reprehenderit dolor beatae ea dolores neque\n'
          'fugiat blanditiis voluptate porro vel nihil molestiae ut '
          'reiciendis\n'
          'qui aperiam non debitis possimus qui neque nisi nulla',
  'id': 2,
  'title': 'qui est esse',
  'userId': 1},
 {'body': 'et iusto sed quo iure\n'
          'voluptatem occaecati omnis eligendi aut ad\n'
          'voluptatem doloribus vel accusantium quis pariatur\n'
          'molestiae porro eius odio et labore et velit aut',
  'id': 3,
  'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut',
  'userId': 1},
 {'body': 'ullam et saepe reiciendis voluptatem adipisci\n'
          'sit amet autem assumenda provident rerum culpa\n'
          'quis hic commodi nesciunt rem tenetur doloremque ipsam iure\n'
          'quis sunt voluptatem rerum illo velit',
  'id': 4,
  'title': 'eum et est occaecati',
  'userId': 1},
 {'body': 'repudiandae veniam quaerat sunt sed\n'
          'alias aut fugiat sit autem sed est\n'
          'voluptatem omnis possimus esse voluptatibus quis\n'
          'est aut tenetur dolor neque',
  'id': 5,
  'title': 'nesciunt quas odio',
  'userId': 1},
 {'body': 'ut aspernatur corporis harum nihil quis provident sequi\n'
          'mollitia nobis aliquid molestiae\n'
          'perspiciatis et ea nemo ab reprehenderit accusantium quas\n'
          'voluptate dolores velit et doloremque molestiae',
  'id': 6,
  'title': 'dolorem eum magni eos aperiam quia',
  'userId': 1},
 {'body': 'dolore placeat quibusdam ea quo vitae\n'
          'magni quis enim qui quis quo nemo aut saepe\n'
          'quidem repellat excepturi ut quia\n'
          'sunt ut sequi eos ea sed quas',
  'id': 7,
  'title': 'magnam facilis autem',
  'userId': 1},
 {'body': 'dignissimos aperiam dolorem qui eum\n'
          'facilis quibusdam animi sint suscipit qui sint possimus cum\n'
          'quaerat magni maiores excepturi\n'
          'ipsam ut commodi dolor voluptatum modi aut vitae',
  'id': 8,
  'title': 'dolorem dolore est ipsam',
  'userId': 1},
 {'body': 'consectetur animi nesciunt iure dolore\n'
          'enim quia ad\n'
          'veniam autem ut quam aut nobis\n'
          'et est aut quod aut provident voluptas autem voluptas',
  'id': 9,
  'title': 'nesciunt iure omnis dolorem tempora et accusantium',
  'userId': 1},
 {'body': 'quo et expedita modi cum officia vel magni\n'
          'doloribus qui repudiandae\n'
          'vero nisi sit\n'
          'quos veniam quod sed accusamus veritatis error',
  'id': 10,
  'title': 'optio molestias id quia eum',
  'userId': 1},
 {'body': 'delectus reiciendis molestiae occaecati non minima eveniet qui '
          'voluptatibus\n'
          'accusamus in eum beatae sit\n'
          'vel qui neque voluptates ut commodi qui incidunt\n'
          'ut animi commodi',
  'id': 11,
  'title': 'et ea vero quia laudantium autem',
  'userId': 2},
 {'body': 'itaque id aut magnam\n'
          'praesentium quia et ea odit et ea voluptas et\n'
          'sapiente quia nihil amet occaecati quia id voluptatem\n'
          'incidunt ea est distinctio odio',
  'id': 12,
  'title': 'in quibusdam tempore odit est dolorem',
  'userId': 2},
 {'body': 'aut dicta possimus sint mollitia voluptas commodi quo doloremque\n'
          'iste corrupti reiciendis voluptatem eius rerum\n'
          'sit cumque quod eligendi laborum minima\n'
          'perferendis recusandae assumenda consectetur porro architecto ipsum '
          'ipsam',
  'id': 13,
  'title': 'dolorum ut in voluptas mollitia et saepe quo animi',
  'userId': 2},
 {'body': 'fuga et accusamus dolorum perferendis illo voluptas\n'
          'non doloremque neque facere\n'
          'ad qui dolorum molestiae beatae\n'
          'sed aut voluptas totam sit illum',
  'id': 14,
  'title': 'voluptatem eligendi optio',
  'userId': 2},
 {'body': 'reprehenderit quos placeat\n'
          'velit minima officia dolores impedit repudiandae molestiae nam\n'
          'voluptas recusandae quis delectus\n'
          'officiis harum fugiat vitae',
  'id': 15,
  'title': 'eveniet quod temporibus',
  'userId': 2},
 {'body': 'suscipit nam nisi quo aperiam aut\n'
          'asperiores eos fugit maiores voluptatibus quia\n'
          'voluptatem quis ullam qui in alias quia est\n'
          'consequatur magni mollitia accusamus ea nisi voluptate dicta',
  'id': 16,
  'title': 'sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam '
           'odio',
  'userId': 2},
 {'body': 'eos voluptas et aut odit natus earum\n'
          'aspernatur fuga molestiae ullam\n'
          'deserunt ratione qui eos\n'
          'qui nihil ratione nemo velit ut aut id quo',
  'id': 17,
  'title': 'fugit voluptas sed molestias voluptatem provident',
  'userId': 2},
 {'body': 'eveniet quo quis\n'
          'laborum totam consequatur non dolor\n'
          'ut et est repudiandae\n'
          'est voluptatem vel debitis et magnam',
  'id': 18,
  'title': 'voluptate et itaque vero tempora molestiae',
  'userId': 2},
 {'body': 'illum quis cupiditate provident sit magnam\n'
          'ea sed aut omnis\n'
          'veniam maiores ullam consequatur atque\n'
          'adipisci quo iste expedita sit quos voluptas',
  'id': 19,
  'title': 'adipisci placeat illum aut reiciendis qui',
  'userId': 2},
 {'body': 'qui consequuntur ducimus possimus quisquam amet similique\n'
          'suscipit porro ipsam amet\n'
          'eos veritatis officiis exercitationem vel fugit aut necessitatibus '
          'totam\n'
          'omnis rerum consequatur expedita quidem cumque explicabo',
  'id': 20,
  'title': 'doloribus ad provident suscipit at',
  'userId': 2},
 {'body': 'repellat aliquid praesentium dolorem quo\n'
          'sed totam minus non itaque\n'
          'nihil labore molestiae sunt dolor eveniet hic recusandae veniam\n'
          'tempora et tenetur expedita sunt',
  'id': 21,
  'title': 'asperiores ea ipsam voluptatibus modi minima quia sint',
  'userId': 3},
 {'body': 'eos qui et ipsum ipsam suscipit aut\n'
          'sed omnis non odio\n'
          'expedita earum mollitia molestiae aut atque rem suscipit\n'
          'nam impedit esse',
  'id': 22,
  'title': 'dolor sint quo a velit explicabo quia nam',
  'userId': 3},
 {'body': 'veritatis unde neque eligendi\n'
          'quae quod architecto quo neque vitae\n'
          'est illo sit tempora doloremque fugit quod\n'
          'et et vel beatae sequi ullam sed tenetur perspiciatis',
  'id': 23,
  'title': 'maxime id vitae nihil numquam',
  'userId': 3},
 {'body': 'enim et ex nulla\n'
          'omnis voluptas quia qui\n'
          'voluptatem consequatur numquam aliquam sunt\n'
          'totam recusandae id dignissimos aut sed asperiores deserunt',
  'id': 24,
  'title': 'autem hic labore sunt dolores incidunt',
  'userId': 3},
 {'body': 'ullam consequatur ut\n'
          'omnis quis sit vel consequuntur\n'
          'ipsa eligendi ipsum molestiae et omnis error nostrum\n'
          'molestiae illo tempore quia et distinctio',
  'id': 25,
  'title': 'rem alias distinctio quo quis',
  'userId': 3},
 {'body': 'similique esse doloribus nihil accusamus\n'
          'omnis dolorem fuga consequuntur reprehenderit fugit recusandae '
          'temporibus\n'
          'perspiciatis cum ut laudantium\n'
          'omnis aut molestiae vel vero',
  'id': 26,
  'title': 'est et quae odit qui non',
  'userId': 3},
 {'body': 'eum sed dolores ipsam sint possimus debitis occaecati\n'
          'debitis qui qui et\n'
          'ut placeat enim earum aut odit facilis\n'
          'consequatur suscipit necessitatibus rerum sed inventore temporibus '
          'consequatur',
  'id': 27,
  'title': 'quasi id et eos tenetur aut quo autem',
  'userId': 3},
 {'body': 'non et quaerat ex quae ad maiores\n'
          'maiores recusandae totam aut blanditiis mollitia quas illo\n'
          'ut voluptatibus voluptatem\n'
          'similique nostrum eum',
  'id': 28,
  'title': 'delectus ullam et corporis nulla voluptas sequi',
  'userId': 3},
 {'body': 'odit magnam ut saepe sed non qui\n'
          'tempora atque nihil\n'
          'accusamus illum doloribus illo dolor\n'
          'eligendi repudiandae odit magni similique sed cum maiores',
  'id': 29,
  'title': 'iusto eius quod necessitatibus culpa ea',
  'userId': 3},
 {'body': 'alias dolor cumque\n'
          'impedit blanditiis non eveniet odio maxime\n'
          'blanditiis amet eius quis tempora quia autem rem\n'
          'a provident perspiciatis quia',
  'id': 30,
  'title': 'a quo magni similique perferendis',
  'userId': 3},
 {'body': 'debitis eius sed quibusdam non quis consectetur vitae\n'
          'impedit ut qui consequatur sed aut in\n'
          'quidem sit nostrum et maiores adipisci atque\n'
          'quaerat voluptatem adipisci repudiandae',
  'id': 31,
  'title': 'ullam ut quidem id aut vel consequuntur',
  'userId': 4},
 {'body': 'deserunt eos nobis asperiores et hic\n'
          'est debitis repellat molestiae optio\n'
          'nihil ratione ut eos beatae quibusdam distinctio maiores\n'
          'earum voluptates et aut adipisci ea maiores voluptas maxime',
  'id': 32,
  'title': 'doloremque illum aliquid sunt',
  'userId': 4},
 {'body': 'rerum ut et numquam laborum odit est sit\n'
          'id qui sint in\n'
          'quasi tenetur tempore aperiam et quaerat qui in\n'
          'rerum officiis sequi cumque quod',
  'id': 33,
  'title': 'qui explicabo molestiae dolorem',
  'userId': 4},
 {'body': 'ea velit perferendis earum ut voluptatem voluptate itaque iusto\n'
          'totam pariatur in\n'
          'nemo voluptatem voluptatem autem magni tempora minima in\n'
          'est distinctio qui assumenda accusamus dignissimos officia nesciunt '
          'nobis',
  'id': 34,
  'title': 'magnam ut rerum iure',
  'userId': 4},
 {'body': 'nisi error delectus possimus ut eligendi vitae\n'
          'placeat eos harum cupiditate facilis reprehenderit voluptatem '
          'beatae\n'
          'modi ducimus quo illum voluptas eligendi\n'
          'et nobis quia fugit',
  'id': 35,
  'title': 'id nihil consequatur molestias animi provident',
  'userId': 4},
 {'body': 'ad mollitia et omnis minus architecto odit\n'
          'voluptas doloremque maxime aut non ipsa qui alias veniam\n'
          'blanditiis culpa aut quia nihil cumque facere et occaecati\n'
          'qui aspernatur quia eaque ut aperiam inventore',
  'id': 36,
  'title': 'fuga nam accusamus voluptas reiciendis itaque',
  'userId': 4},
 {'body': 'debitis et eaque non officia sed nesciunt pariatur vel\n'
          'voluptatem iste vero et ea\n'
          'numquam aut expedita ipsum nulla in\n'
          'voluptates omnis consequatur aut enim officiis in quam qui',
  'id': 37,
  'title': 'provident vel ut sit ratione est',
  'userId': 4},
 {'body': 'animi esse sit aut sit nesciunt assumenda eum voluptas\n'
          'quia voluptatibus provident quia necessitatibus ea\n'
          'rerum repudiandae quia voluptatem delectus fugit aut id quia\n'
          'ratione optio eos iusto veniam iure',
  'id': 38,
  'title': 'explicabo et eos deleniti nostrum ab id repellendus',
  'userId': 4},
 {'body': 'corporis rerum ducimus vel eum accusantium\n'
          'maxime aspernatur a porro possimus iste omnis\n'
          'est in deleniti asperiores fuga aut\n'
          'voluptas sapiente vel dolore minus voluptatem incidunt ex',
  'id': 39,
  'title': 'eos dolorem iste accusantium est eaque quam',
  'userId': 4},
 {'body': 'ut voluptatum aliquid illo tenetur nemo sequi quo facilis\n'
          'ipsum rem optio mollitia quas\n'
          'voluptatem eum voluptas qui\n'
          'unde omnis voluptatem iure quasi maxime voluptas nam',
  'id': 40,
  'title': 'enim quo cumque',
  'userId': 4},
 {'body': 'molestias id nostrum\n'
          'excepturi molestiae dolore omnis repellendus quaerat saepe\n'
          'consectetur iste quaerat tenetur asperiores accusamus ex ut\n'
          'nam quidem est ducimus sunt debitis saepe',
  'id': 41,
  'title': 'non est facere',
  'userId': 5},
 {'body': 'odio fugit voluptatum ducimus earum autem est incidunt voluptatem\n'
          'odit reiciendis aliquam sunt sequi nulla dolorem\n'
          'non facere repellendus voluptates quia\n'
          'ratione harum vitae ut',
  'id': 42,
  'title': 'commodi ullam sint et excepturi error explicabo praesentium '
           'voluptas',
  'userId': 5},
 {'body': 'similique fugit est\n'
          'illum et dolorum harum et voluptate eaque quidem\n'
          'exercitationem quos nam commodi possimus cum odio nihil nulla\n'
          'dolorum exercitationem magnam ex et a et distinctio debitis',
  'id': 43,
  'title': 'eligendi iste nostrum consequuntur adipisci praesentium sit beatae '
           'perferendis',
  'userId': 5},
 {'body': 'temporibus est consectetur dolore\n'
          'et libero debitis vel velit laboriosam quia\n'
          'ipsum quibusdam qui itaque fuga rem aut\n'
          'ea et iure quam sed maxime ut distinctio quae',
  'id': 44,
  'title': 'optio dolor molestias sit',
  'userId': 5},
 {'body': 'est natus reiciendis nihil possimus aut provident\n'
          'ex et dolor\n'
          'repellat pariatur est\n'
          'nobis rerum repellendus dolorem autem',
  'id': 45,
  'title': 'ut numquam possimus omnis eius suscipit laudantium iure',
  'userId': 5},
 {'body': 'voluptatem quisquam iste\n'
          'voluptatibus natus officiis facilis dolorem\n'
          'quis quas ipsam\n'
          'vel et voluptatum in aliquid',
  'id': 46,
  'title': 'aut quo modi neque nostrum ducimus',
  'userId': 5},
 {'body': 'voluptatem assumenda ut qui ut cupiditate aut impedit veniam\n'
          'occaecati nemo illum voluptatem laudantium\n'
          'molestiae beatae rerum ea iure soluta nostrum\n'
          'eligendi et voluptate',
  'id': 47,
  'title': 'quibusdam cumque rem aut deserunt',
  'userId': 5},
 {'body': 'voluptates quo voluptatem facilis iure occaecati\n'
          'vel assumenda rerum officia et\n'
          'illum perspiciatis ab deleniti\n'
          'laudantium repellat ad ut et autem reprehenderit',
  'id': 48,
  'title': 'ut voluptatem illum ea doloribus itaque eos',
  'userId': 5},
 {'body': 'inventore ab sint\n'
          'natus fugit id nulla sequi architecto nihil quaerat\n'
          'eos tenetur in in eum veritatis non\n'
          'quibusdam officiis aspernatur cumque aut commodi aut',
  'id': 49,
  'title': 'laborum non sunt aut ut assumenda perspiciatis voluptas',
  'userId': 5},
 {'body': 'error suscipit maxime adipisci consequuntur recusandae\n'
          'voluptas eligendi et est et voluptates\n'
          'quia distinctio ab amet quaerat molestiae et vitae\n'
          'adipisci impedit sequi nesciunt quis consectetur',
  'id': 50,
  'title': 'repellendus qui recusandae incidunt voluptates tenetur qui omnis '
           'exercitationem',
  'userId': 5},
 {'body': 'sunt dolores aut doloribus\n'
          'dolore doloribus voluptates tempora et\n'
          'doloremque et quo\n'
          'cum asperiores sit consectetur dolorem',
  'id': 51,
  'title': 'soluta aliquam aperiam consequatur illo quis voluptas',
  'userId': 6},
 {'body': 'iusto est quibusdam fuga quas quaerat molestias\n'
          'a enim ut sit accusamus enim\n'
          'temporibus iusto accusantium provident architecto\n'
          'soluta esse reprehenderit qui laborum',
  'id': 52,
  'title': 'qui enim et consequuntur quia animi quis voluptate quibusdam',
  'userId': 6},
 {'body': 'minima harum praesentium eum rerum illo dolore\n'
          'quasi exercitationem rerum nam\n'
          'porro quis neque quo\n'
          'consequatur minus dolor quidem veritatis sunt non explicabo '
          'similique',
  'id': 53,
  'title': 'ut quo aut ducimus alias',
  'userId': 6},
 {'body': 'totam corporis dignissimos\n'
          'vitae dolorem ut occaecati accusamus\n'
          'ex velit deserunt\n'
          'et exercitationem vero incidunt corrupti mollitia',
  'id': 54,
  'title': 'sit asperiores ipsam eveniet odio non quia',
  'userId': 6},
 {'body': 'debitis excepturi ea perferendis harum libero optio\n'
          'eos accusamus cum fuga ut sapiente repudiandae\n'
          'et ut incidunt omnis molestiae\n'
          'nihil ut eum odit',
  'id': 55,
  'title': 'sit vel voluptatem et non libero',
  'userId': 6},
 {'body': 'aut est omnis dolores\n'
          'neque rerum quod ea rerum velit pariatur beatae excepturi\n'
          'et provident voluptas corrupti\n'
          'corporis harum reprehenderit dolores eligendi',
  'id': 56,
  'title': 'qui et at rerum necessitatibus',
  'userId': 6},
 {'body': 'at pariatur consequuntur earum quidem\n'
          'quo est laudantium soluta voluptatem\n'
          'qui ullam et est\n'
          'et cum voluptas voluptatum repellat est',
  'id': 57,
  'title': 'sed ab est est',
  'userId': 6},
 {'body': 'veniam voluptatum quae adipisci id\n'
          'et id quia eos ad et dolorem\n'
          'aliquam quo nisi sunt eos impedit error\n'
          'ad similique veniam',
  'id': 58,
  'title': 'voluptatum itaque dolores nisi et quasi',
  'userId': 6},
 {'body': 'perspiciatis et quam ea autem temporibus non voluptatibus qui\n'
          'beatae a earum officia nesciunt dolores suscipit voluptas et\n'
          'animi doloribus cum rerum quas et magni\n'
          'et hic ut ut commodi expedita sunt',
  'id': 59,
  'title': 'qui commodi dolor at maiores et quis id accusantium',
  'userId': 6},
 {'body': 'asperiores sunt ab assumenda cumque modi velit\n'
          'qui esse omnis\n'
          'voluptate et fuga perferendis voluptas\n'
          'illo ratione amet aut et omnis',
  'id': 60,
  'title': 'consequatur placeat omnis quisquam quia reprehenderit fugit '
           'veritatis facere',
  'userId': 6},
 {'body': 'ab nemo optio odio\n'
          'delectus tenetur corporis similique nobis repellendus rerum omnis '
          'facilis\n'
          'vero blanditiis debitis in nesciunt doloribus dicta dolores\n'
          'magnam minus velit',
  'id': 61,
  'title': 'voluptatem doloribus consectetur est ut ducimus',
  'userId': 7},
 {'body': 'enim aspernatur illo distinctio quae praesentium\n'
          'beatae alias amet delectus qui voluptate distinctio\n'
          'odit sint accusantium autem omnis\n'
          'quo molestiae omnis ea eveniet optio',
  'id': 62,
  'title': 'beatae enim quia vel',
  'userId': 7},
 {'body': 'enim adipisci aspernatur nemo\n'
          'numquam omnis facere dolorem dolor ex quis temporibus incidunt\n'
          'ab delectus culpa quo reprehenderit blanditiis asperiores\n'
          'accusantium ut quam in voluptatibus voluptas ipsam dicta',
  'id': 63,
  'title': 'voluptas blanditiis repellendus animi ducimus error sapiente et '
           'suscipit',
  'userId': 7},
 {'body': 'id velit blanditiis\n'
          'eum ea voluptatem\n'
          'molestiae sint occaecati est eos perspiciatis\n'
          'incidunt a error provident eaque aut aut qui',
  'id': 64,
  'title': 'et fugit quas eum in in aperiam quod',
  'userId': 7},
 {'body': 'voluptatibus ex esse\n'
          'sint explicabo est aliquid cumque adipisci fuga repellat labore\n'
          'molestiae corrupti ex saepe at asperiores et perferendis\n'
          'natus id esse incidunt pariatur',
  'id': 65,
  'title': 'consequatur id enim sunt et et',
  'userId': 7},
 {'body': 'officia veritatis tenetur vero qui itaque\n'
          'sint non ratione\n'
          'sed et ut asperiores iusto eos molestiae nostrum\n'

In [5]:
pp.pprint(users)

[{'address': {'city': 'Gwenborough',
              'geo': {'lat': '-37.3159', 'lng': '81.1496'},
              'street': 'Kulas Light',
              'suite': 'Apt. 556',
              'zipcode': '92998-3874'},
  'company': {'bs': 'harness real-time e-markets',
              'catchPhrase': 'Multi-layered client-server neural-net',
              'name': 'Romaguera-Crona'},
  'email': 'Sincere@april.biz',
  'id': 1,
  'name': 'Leanne Graham',
  'phone': '1-770-736-8031 x56442',
  'username': 'Bret',
  'website': 'hildegard.org'},
 {'address': {'city': 'Wisokyburgh',
              'geo': {'lat': '-43.9509', 'lng': '-34.4618'},
              'street': 'Victor Plains',
              'suite': 'Suite 879',
              'zipcode': '90566-7771'},
  'company': {'bs': 'synergize scalable supply-chains',
              'catchPhrase': 'Proactive didactic contingency',
              'name': 'Deckow-Crist'},
  'email': 'Shanna@melissa.tv',
  'id': 2,
  'name': 'Ervin Howell',
  'phone': '010-692-6593 x09125',
  'username': 'Antonette',
  'website': 'anastasia.net'},
 {'address': {'city': 'McKenziehaven',
              'geo': {'lat': '-68.6102', 'lng': '-47.0653'},
              'street': 'Douglas Extension',
              'suite': 'Suite 847',
              'zipcode': '59590-4157'},
  'company': {'bs': 'e-enable strategic applications',
              'catchPhrase': 'Face to face bifurcated interface',
              'name': 'Romaguera-Jacobson'},
  'email': 'Nathan@yesenia.net',
  'id': 3,
  'name': 'Clementine Bauch',
  'phone': '1-463-123-4447',
  'username': 'Samantha',
  'website': 'ramiro.info'},
 {'address': {'city': 'South Elvis',
              'geo': {'lat': '29.4572', 'lng': '-164.2990'},
              'street': 'Hoeger Mall',
              'suite': 'Apt. 692',
              'zipcode': '53919-4257'},
  'company': {'bs': 'transition cutting-edge web services',
              'catchPhrase': 'Multi-tiered zero tolerance productivity',
              'name': 'Robel-Corkery'},
  'email': 'Julianne.OConner@kory.org',
  'id': 4,
  'name': 'Patricia Lebsack',
  'phone': '493-170-9623 x156',
  'username': 'Karianne',
  'website': 'kale.biz'},
 {'address': {'city': 'Roscoeview',
              'geo': {'lat': '-31.8129', 'lng': '62.5342'},
              'street': 'Skiles Walks',
              'suite': 'Suite 351',
              'zipcode': '33263'},
  'company': {'bs': 'revolutionize end-to-end systems',
              'catchPhrase': 'User-centric fault-tolerant solution',
              'name': 'Keebler LLC'},
  'email': 'Lucio_Hettinger@annie.ca',
  'id': 5,
  'name': 'Chelsey Dietrich',
  'phone': '(254)954-1289',
  'username': 'Kamren',
  'website': 'demarco.info'},
 {'address': {'city': 'South Christy',
              'geo': {'lat': '-71.4197', 'lng': '71.7478'},
              'street': 'Norberto Crossing',
              'suite': 'Apt. 950',
              'zipcode': '23505-1337'},
  'company': {'bs': 'e-enable innovative applications',
              'catchPhrase': 'Synchronised bottom-line interface',
              'name': 'Considine-Lockman'},
  'email': 'Karley_Dach@jasper.info',
  'id': 6,
  'name': 'Mrs. Dennis Schulist',
  'phone': '1-477-935-8478 x6430',
  'username': 'Leopoldo_Corkery',
  'website': 'ola.org'},
 {'address': {'city': 'Howemouth',
              'geo': {'lat': '24.8918', 'lng': '21.8984'},
              'street': 'Rex Trail',
              'suite': 'Suite 280',
              'zipcode': '58804-1099'},
  'company': {'bs': 'generate enterprise e-tailers',
              'catchPhrase': 'Configurable multimedia task-force',
              'name': 'Johns Group'},
  'email': 'Telly.Hoeger@billy.biz',
  'id': 7,
  'name': 'Kurtis Weissnat',
  'phone': '210.067.6132',
  'username': 'Elwyn.Skiles',
  'website': 'elvis.io'},
 {'address': {'city': 'Aliyaview',
              'geo': {'lat': '-14.3990', 'lng': '-120.7677'},
              'street': 'Ellsworth Summit',
              'suite': 'Suite 729',
              'zipcode': '45169'},
  'company': {'bs': 'e-enable extensible e-tailers',
              'catchPhrase': 'Implemented secondary concept',
              'name': 'Abernathy Group'},
  'email': 'Sherwood@rosamond.me',
  'id': 8,
  'name': 'Nicholas Runolfsdottir V',
  'phone': '586.493.6943 x140',
  'username': 'Maxime_Nienow',
  'website': 'jacynthe.com'},
 {'address': {'city': 'Bartholomebury',
              'geo': {'lat': '24.6463', 'lng': '-168.8889'},
              'street': 'Dayna Park',
              'suite': 'Suite 449',
              'zipcode': '76495-3109'},
  'company': {'bs': 'aggregate real-time technologies',
              'catchPhrase': 'Switchable contextually-based project',
              'name': 'Yost and Sons'},
  'email': 'Chaim_McDermott@dana.io',
  'id': 9,
  'name': 'Glenna Reichert',
  'phone': '(775)976-6794 x41206',
  'username': 'Delphine',
  'website': 'conrad.com'},
 {'address': {'city': 'Lebsackbury',
              'geo': {'lat': '-38.2386', 'lng': '57.2232'},
              'street': 'Kattie Turnpike',
              'suite': 'Suite 198',
              'zipcode': '31428-2261'},
  'company': {'bs': 'target end-to-end models',
              'catchPhrase': 'Centralized empowering task-force',
              'name': 'Hoeger LLC'},
  'email': 'Rey.Padberg@karina.biz',
  'id': 10,
  'name': 'Clementina DuBuque',
  'phone': '024-648-3804',
  'username': 'Moriah.Stanton',
  'website': 'ambrose.net'}]

In [6]:
pp.pprint(todos)

[{'completed': False, 'id': 1, 'title': 'delectus aut autem', 'userId': 1},
 {'completed': False,
  'id': 2,
  'title': 'quis ut nam facilis et officia qui',
  'userId': 1},
 {'completed': False, 'id': 3, 'title': 'fugiat veniam minus', 'userId': 1},
 {'completed': True, 'id': 4, 'title': 'et porro tempora', 'userId': 1},
 {'completed': False,
  'id': 5,
  'title': 'laboriosam mollitia et enim quasi adipisci quia provident illum',
  'userId': 1},
 {'completed': False,
  'id': 6,
  'title': 'qui ullam ratione quibusdam voluptatem quia omnis',
  'userId': 1},
 {'completed': False,
  'id': 7,
  'title': 'illo expedita consequatur quia in',
  'userId': 1},
 {'completed': True,
  'id': 8,
  'title': 'quo adipisci enim quam ut ab',
  'userId': 1},
 {'completed': False,
  'id': 9,
  'title': 'molestiae perspiciatis ipsa',
  'userId': 1},
 {'completed': True,
  'id': 10,
  'title': 'illo est ratione doloremque quia maiores aut',
  'userId': 1},
 {'completed': True,
  'id': 11,
  'title': 'vero rerum temporibus dolor',
  'userId': 1},
 {'completed': True,
  'id': 12,
  'title': 'ipsa repellendus fugit nisi',
  'userId': 1},
 {'completed': False, 'id': 13, 'title': 'et doloremque nulla', 'userId': 1},
 {'completed': True,
  'id': 14,
  'title': 'repellendus sunt dolores architecto voluptatum',
  'userId': 1},
 {'completed': True,
  'id': 15,
  'title': 'ab voluptatum amet voluptas',
  'userId': 1},
 {'completed': True,
  'id': 16,
  'title': 'accusamus eos facilis sint et aut voluptatem',
  'userId': 1},
 {'completed': True,
  'id': 17,
  'title': 'quo laboriosam deleniti aut qui',
  'userId': 1},
 {'completed': False,
  'id': 18,
  'title': 'dolorum est consequatur ea mollitia in culpa',
  'userId': 1},
 {'completed': True,
  'id': 19,
  'title': 'molestiae ipsa aut voluptatibus pariatur dolor nihil',
  'userId': 1},
 {'completed': True,
  'id': 20,
  'title': 'ullam nobis libero sapiente ad optio sint',
  'userId': 1},
 {'completed': False,
  'id': 21,
  'title': 'suscipit repellat esse quibusdam voluptatem incidunt',
  'userId': 2},
 {'completed': True,
  'id': 22,
  'title': 'distinctio vitae autem nihil ut molestias quo',
  'userId': 2},
 {'completed': False,
  'id': 23,
  'title': 'et itaque necessitatibus maxime molestiae qui quas velit',
  'userId': 2},
 {'completed': False,
  'id': 24,
  'title': 'adipisci non ad dicta qui amet quaerat doloribus ea',
  'userId': 2},
 {'completed': True,
  'id': 25,
  'title': 'voluptas quo tenetur perspiciatis explicabo natus',
  'userId': 2},
 {'completed': True, 'id': 26, 'title': 'aliquam aut quasi', 'userId': 2},
 {'completed': True,
  'id': 27,
  'title': 'veritatis pariatur delectus',
  'userId': 2},
 {'completed': False,
  'id': 28,
  'title': 'nesciunt totam sit blanditiis sit',
  'userId': 2},
 {'completed': False, 'id': 29, 'title': 'laborum aut in quam', 'userId': 2},
 {'completed': True,
  'id': 30,
  'title': 'nemo perspiciatis repellat ut dolor libero commodi blanditiis '
           'omnis',
  'userId': 2},
 {'completed': False,
  'id': 31,
  'title': 'repudiandae totam in est sint facere fuga',
  'userId': 2},
 {'completed': False,
  'id': 32,
  'title': 'earum doloribus ea doloremque quis',
  'userId': 2},
 {'completed': False, 'id': 33, 'title': 'sint sit aut vero', 'userId': 2},
 {'completed': False,
  'id': 34,
  'title': 'porro aut necessitatibus eaque distinctio',
  'userId': 2},
 {'completed': True,
  'id': 35,
  'title': 'repellendus veritatis molestias dicta incidunt',
  'userId': 2},
 {'completed': True,
  'id': 36,
  'title': 'excepturi deleniti adipisci voluptatem et neque optio illum ad',
  'userId': 2},
 {'completed': False, 'id': 37, 'title': 'sunt cum tempora', 'userId': 2},
 {'completed': False, 'id': 38, 'title': 'totam quia non', 'userId': 2},
 {'completed': False,
  'id': 39,
  'title': 'doloremque quibusdam asperiores libero corrupti illum qui omnis',
  'userId': 2},
 {'completed': True,
  'id': 40,
  'title': 'totam atque quo nesciunt',
  'userId': 2},
 {'completed': False,
  'id': 41,
  'title': 'aliquid amet impedit consequatur aspernatur placeat eaque fugiat '
           'suscipit',
  'userId': 3},
 {'completed': False,
  'id': 42,
  'title': 'rerum perferendis error quia ut eveniet',
  'userId': 3},
 {'completed': True,
  'id': 43,
  'title': 'tempore ut sint quis recusandae',
  'userId': 3},
 {'completed': True,
  'id': 44,
  'title': 'cum debitis quis accusamus doloremque ipsa natus sapiente omnis',
  'userId': 3},
 {'completed': False,
  'id': 45,
  'title': 'velit soluta adipisci molestias reiciendis harum',
  'userId': 3},
 {'completed': False,
  'id': 46,
  'title': 'vel voluptatem repellat nihil placeat corporis',
  'userId': 3},
 {'completed': False,
  'id': 47,
  'title': 'nam qui rerum fugiat accusamus',
  'userId': 3},
 {'completed': False,
  'id': 48,
  'title': 'sit reprehenderit omnis quia',
  'userId': 3},
 {'completed': False,
  'id': 49,
  'title': 'ut necessitatibus aut maiores debitis officia blanditiis velit et',
  'userId': 3},
 {'completed': True,
  'id': 50,
  'title': 'cupiditate necessitatibus ullam aut quis dolor voluptate',
  'userId': 3},
 {'completed': False,
  'id': 51,
  'title': 'distinctio exercitationem ab doloribus',
  'userId': 3},
 {'completed': False,
  'id': 52,
  'title': 'nesciunt dolorum quis recusandae ad pariatur ratione',
  'userId': 3},
 {'completed': False,
  'id': 53,
  'title': 'qui labore est occaecati recusandae aliquid quam',
  'userId': 3},
 {'completed': True,
  'id': 54,
  'title': 'quis et est ut voluptate quam dolor',
  'userId': 3},
 {'completed': True,
  'id': 55,
  'title': 'voluptatum omnis minima qui occaecati provident nulla voluptatem '
           'ratione',
  'userId': 3},
 {'completed': True,
  'id': 56,
  'title': 'deleniti ea temporibus enim',
  'userId': 3},
 {'completed': False,
  'id': 57,
  'title': 'pariatur et magnam ea doloribus similique voluptatem rerum quia',
  'userId': 3},
 {'completed': False,
  'id': 58,
  'title': 'est dicta totam qui explicabo doloribus qui dignissimos',
  'userId': 3},
 {'completed': False,
  'id': 59,
  'title': 'perspiciatis velit id laborum placeat iusto et aliquam odio',
  'userId': 3},
 {'completed': True,
  'id': 60,
  'title': 'et sequi qui architecto ut adipisci',
  'userId': 3},
 {'completed': True,
  'id': 61,
  'title': 'odit optio omnis qui sunt',
  'userId': 4},
 {'completed': False,
  'id': 62,
  'title': 'et placeat et tempore aspernatur sint numquam',
  'userId': 4},
 {'completed': True,
  'id': 63,
  'title': 'doloremque aut dolores quidem fuga qui nulla',
  'userId': 4},
 {'completed': False,
  'id': 64,
  'title': 'voluptas consequatur qui ut quia magnam nemo esse',
  'userId': 4},
 {'completed': False,
  'id': 65,
  'title': 'fugiat pariatur ratione ut asperiores necessitatibus magni',
  'userId': 4},
 {'completed': False,
  'id': 66,
  'title': 'rerum eum molestias autem voluptatum sit optio',
  'userId': 4},
 {'completed': False,
  'id': 67,
  'title': 'quia voluptatibus voluptatem quos similique maiores repellat',
  'userId': 4},
 {'completed': False,
  'id': 68,
  'title': 'aut id perspiciatis voluptatem iusto',
  'userId': 4},
 {'completed': False,
  'id': 69,
  'title': 'doloribus sint dolorum ab adipisci itaque dignissimos aliquam '
           'suscipit',
  'userId': 4},
 {'completed': False,
  'id': 70,
  'title': 'ut sequi accusantium et mollitia delectus sunt',
  'userId': 4},
 {'completed': False, 'id': 71, 'title': 'aut velit saepe ullam', 'userId': 4},
 {'completed': False,
  'id': 72,
  'title': 'praesentium facilis facere quis harum voluptatibus voluptatem eum',
  'userId': 4},
 {'completed': True,
  'id': 73,
  'title': 'sint amet quia totam corporis qui exercitationem commodi',
  'userId': 4},
 {'completed': False,
  'id': 74,
  'title': 'expedita tempore nobis eveniet laborum maiores',
  'userId': 4},
 {'completed': False,
  'id': 75,
  'title': 'occaecati adipisci est possimus totam',
  'userId': 4},
 {'completed': True, 'id': 76, 'title': 'sequi dolorem sed', 'userId': 4},
 {'completed': False,
  'id': 77,
  'title': 'maiores aut nesciunt delectus exercitationem vel assumenda '
           'eligendi at',
  'userId': 4},
 {'completed': False,
  'id': 78,
  'title': 'reiciendis est magnam amet nemo iste recusandae impedit quaerat',
  'userId': 4},
 {'completed': True, 'id': 79, 'title': 'eum ipsa maxime ut', 'userId': 4},
 {'completed': True,
  'id': 80,
  'title': 'tempore molestias dolores rerum sequi voluptates ipsum consequatur',
  'userId': 4},
 {'completed': True, 'id': 81, 'title': 'suscipit qui totam', 'userId': 5},
 {'completed': False,
  'id': 82,
  'title': 'voluptates eum voluptas et dicta',
  'userId': 5},
 {'completed': True,
  'id': 83,
  'title': 'quidem at rerum quis ex aut sit quam',
  'userId': 5},
 {'completed': False,
  'id': 84,
  'title': 'sunt veritatis ut voluptate',
  'userId': 5},
 {'completed': True, 'id': 85, 'title': 'et quia ad iste a', 'userId': 5},
 {'completed': True, 'id': 86, 'title': 'incidunt ut saepe autem', 'userId': 5},
 {'completed': True,
  'id': 87,
  'title': 'laudantium quae eligendi consequatur quia et vero autem',
  'userId': 5},
 {'completed': False,
  'id': 88,
  'title': 'vitae aut excepturi laboriosam sint aliquam et et accusantium',
  'userId': 5},
 {'completed': True, 'id': 89, 'title': 'sequi ut omnis et', 'userId': 5},
 {'completed': True,
  'id': 90,
  'title': 'molestiae nisi accusantium tenetur dolorem et',
  'userId': 5},
 {'completed': True,
  'id': 91,
  'title': 'nulla quis consequatur saepe qui id expedita',
  'userId': 5},
 {'completed': True, 'id': 92, 'title': 'in omnis laboriosam', 'userId': 5},
 {'completed': True,
  'id': 93,
  'title': 'odio iure consequatur molestiae quibusdam necessitatibus quia sint',
  'userId': 5},
 {'completed': False,
  'id': 94,
  'title': 'facilis modi saepe mollitia',
  'userId': 5},
 {'completed': True,
  'id': 95,
  'title': 'vel nihil et molestiae iusto assumenda nemo quo ut',
  'userId': 5},
 {'completed': False,
  'id': 96,
  'title': 'nobis suscipit ducimus enim asperiores voluptas',
  'userId': 5},
 {'completed': False,
  'id': 97,
  'title': 'dolorum laboriosam eos qui iure aliquam',
  'userId': 5},
 {'completed': True,
  'id': 98,
  'title': 'debitis accusantium ut quo facilis nihil quis sapiente '
           'necessitatibus',
  'userId': 5},
 {'completed': False,
  'id': 99,
  'title': 'neque voluptates ratione',
  'userId': 5},
 {'completed': False,
  'id': 100,
  'title': 'excepturi a et neque qui expedita vel voluptate',
  'userId': 5},
 {'completed': False,
  'id': 101,
  'title': 'explicabo enim cumque porro aperiam occaecati minima',
  'userId': 6},
 {'completed': False, 'id': 102, 'title': 'sed ab consequatur', 'userId': 6},
 {'completed': False,
  'id': 103,
  'title': 'non sunt delectus illo nulla tenetur enim omnis',
  'userId': 6},
 {'completed': False,
  'id': 104,
  'title': 'excepturi non laudantium quo',
  'userId': 6},
 {'completed': True,
  'id': 105,
  'title': 'totam quia dolorem et illum repellat voluptas optio',
  'userId': 6},
 {'completed': True,
  'id': 106,
  'title': 'ad illo quis voluptatem temporibus',
  'userId': 6},
 {'completed': False,
  'id': 107,
  'title': 'praesentium facilis omnis laudantium fugit ad iusto nihil nesciunt',
  'userId': 6},
 {'completed': True,
  'id': 108,
  'title': 'a eos eaque nihil et exercitationem incidunt delectus',
  'userId': 6},
 {'completed': True,
  'id': 109,
  'title': 'autem temporibus harum quisquam in culpa',
  'userId': 6},
 {'completed': True, 'id': 110, 'title': 'aut aut ea corporis', 'userId': 6},
 {'completed': False,
  'id': 111,
  'title': 'magni accusantium labore et id quis provident',
  'userId': 6},
 {'completed': False,
  'id': 112,
  'title': 'consectetur impedit quisquam qui deserunt non rerum consequuntur '
           'eius',
  'userId': 6},
 {'completed': False,
  'id': 113,
  'title': 'quia atque aliquam sunt impedit voluptatum rerum assumenda nisi',
  'userId': 6},
 {'completed': False,
  'id': 114,
  'title': 'cupiditate quos possimus corporis quisquam exercitationem beatae',
  'userId': 6},
 {'completed': False, 'id': 115, 'title': 'sed et ea eum', 'userId': 6},
 {'completed': True,
  'id': 116,
  'title': 'ipsa dolores vel facilis ut',
  'userId': 6},
 {'completed': False,
  'id': 117,
  'title': 'sequi quae est et qui qui eveniet asperiores',
  'userId': 6},
 {'completed': False,
  'id': 118,
  'title': 'quia modi consequatur vero fugiat',
  'userId': 6},
 {'completed': False,
  'id': 119,
  'title': 'corporis ducimus ea perspiciatis iste',
  'userId': 6},
 {'completed': False,
  'id': 120,
  'title': 'dolorem laboriosam vel voluptas et aliquam quasi',
  'userId': 6},
 {'completed': True,
  'id': 121,
  'title': 'inventore aut nihil minima laudantium hic qui omnis',
  'userId': 7},
 {'completed': True,
  'id': 122,
  'title': 'provident aut nobis culpa',
  'userId': 7},
 {'completed': False,
  'id': 123,
  'title': 'esse et quis iste est earum aut impedit',
  'userId': 7},
 {'completed': False, 'id': 124, 'title': 'qui consectetur id', 'userId': 7},
 {'completed': False,
  'id': 125,
  'title': 'aut quasi autem iste tempore illum possimus',
  'userId': 7},
 {'completed': True,
  'id': 126,
  'title': 'ut asperiores perspiciatis veniam ipsum rerum saepe',
  'userId': 7},
 {'completed': True,
  'id': 127,
  'title': 'voluptatem libero consectetur rerum ut',
  'userId': 7},
 {'completed': False,
  'id': 128,
  'title': 'eius omnis est qui voluptatem autem',
  'userId': 7},
 {'completed': False,
  'id': 129,
  'title': 'rerum culpa quis harum',
  'userId': 7},
 {'completed': True,
  'id': 130,
  'title': 'nulla aliquid eveniet harum laborum libero alias ut unde',
  'userId': 7},
 {'completed': False, 'id': 131, 'title': 'qui ea incidunt quis', 'userId': 7},
 {'completed': True,
  'id': 132,
  'title': 'qui molestiae voluptatibus velit iure harum quisquam',
  'userId': 7},
 {'completed': True,
  'id': 133,
  'title': 'et labore eos enim rerum consequatur sunt',
  'userId': 7},
 {'completed': False,
  'id': 134,
  'title': 'molestiae doloribus et laborum quod ea',
  'userId': 7},
 {'completed': False,
  'id': 135,
  'title': 'facere ipsa nam eum voluptates reiciendis vero qui',
  'userId': 7},
 {'completed': False,
  'id': 136,
  'title': 'asperiores illo tempora fuga sed ut quasi adipisci',
  'userId': 7},
 {'completed': False, 'id': 137, 'title': 'qui sit non', 'userId': 7},
 {'completed': True,
  'id': 138,
  'title': 'placeat minima consequatur rem qui ut',
  'userId': 7},
 {'completed': False,
  'id': 139,
  'title': 'consequatur doloribus id possimus voluptas a voluptatem',
  'userId': 7},
 {'completed': True,
  'id': 140,
  'title': 'aut consectetur in blanditiis deserunt quia sed laboriosam',
  'userId': 7},
 {'completed': True,
  'id': 141,
  'title': 'explicabo consectetur debitis voluptates quas quae culpa rerum non',
  'userId': 8},
 {'completed': True,
  'id': 142,
  'title': 'maiores accusantium architecto necessitatibus reiciendis ea aut',
  'userId': 8},
 {'completed': False,
  'id': 143,
  'title': 'eum non recusandae cupiditate animi',
  'userId': 8},
 {'completed': False,
  'id': 144,
  'title': 'ut eum exercitationem sint',
  'userId': 8},
 {'completed': False,
  'id': 145,
  'title': 'beatae qui ullam incidunt voluptatem non nisi aliquam',
  'userId': 8},
 {'completed': True,
  'id': 146,
  'title': 'molestiae suscipit ratione nihil odio libero impedit vero totam',
  'userId': 8},
 {'completed': True,
  'id': 147,
  'title': 'eum itaque quod reprehenderit et facilis dolor autem ut',
  'userId': 8},
 {'completed': False,
  'id': 148,
  'title': 'esse quas et quo quasi exercitationem',
  'userId': 8},
 {'completed': False,
  'id': 149,
  'title': 'animi voluptas quod perferendis est',
  'userId': 8},
 {'completed': False,
  'id': 150,
  'title': 'eos amet tempore laudantium fugit a',
  'userId': 8},
 {'completed': True,
  'id': 151,
  'title': 'accusamus adipisci dicta qui quo ea explicabo sed vero',
  'userId': 8},
 {'completed': False,
  'id': 152,
  'title': 'odit eligendi recusandae doloremque cumque non',
  'userId': 8},
 {'completed': False,
  'id': 153,
  'title': 'ea aperiam consequatur qui repellat eos',
  'userId': 8},
 {'completed': True, 'id': 154, 'title': 'rerum non ex sapiente', 'userId': 8},
 {'completed': True,
  'id': 155,
  'title': 'voluptatem nobis consequatur et assumenda magnam',
  'userId': 8},
 {'completed': True,
  'id': 156,
  'title': 'nam quia quia nulla repellat assumenda quibusdam sit nobis',
  'userId': 8},
 {'completed': True,
  'id': 157,
  'title': 'dolorem veniam quisquam deserunt repellendus',
  'userId': 8},
 {'completed': True,
  'id': 158,
  'title': 'debitis vitae delectus et harum accusamus aut deleniti a',
  'userId': 8},
 {'completed': True,
  'id': 159,
  'title': 'debitis adipisci quibusdam aliquam sed dolore ea praesentium nobis',
  'userId': 8},
 {'completed': False,
  'id': 160,
  'title': 'et praesentium aliquam est',
  'userId': 8},
 {'completed': True,
  'id': 161,
  'title': 'ex hic consequuntur earum omnis alias ut occaecati culpa',
  'userId': 9},
 {'completed': True,
  'id': 162,
  'title': 'omnis laboriosam molestias animi sunt dolore',
  'userId': 9},
 {'completed': False,
  'id': 163,
  'title': 'natus corrupti maxime laudantium et voluptatem laboriosam odit',
  'userId': 9},
 {'completed': False,
  'id': 164,
  'title': 'reprehenderit quos aut aut consequatur est sed',
  'userId': 9},
 {'completed': False,
  'id': 165,
  'title': 'fugiat perferendis sed aut quidem',
  'userId': 9},
 {'completed': False,
  'id': 166,
  'title': 'quos quo possimus suscipit minima ut',
  'userId': 9},
 {'completed': False,
  'id': 167,
  'title': 'et quis minus quo a asperiores molestiae',
  'userId': 9},
 {'completed': False,
  'id': 168,
  'title': 'recusandae quia qui sunt libero',
  'userId': 9},
 {'completed': True,
  'id': 169,
  'title': 'ea odio perferendis officiis',
  'userId': 9},
 {'completed': False,
  'id': 170,
  'title': 'quisquam aliquam quia doloribus aut',
  'userId': 9},
 {'completed': True,
  'id': 171,
  'title': 'fugiat aut voluptatibus corrupti deleniti velit iste odio',
  'userId': 9},
 {'completed': False,
  'id': 172,
  'title': 'et provident amet rerum consectetur et voluptatum',
  'userId': 9},
 {'completed': False, 'id': 173, 'title': 'harum ad aperiam quis', 'userId': 9},
 {'completed': False, 'id': 174, 'title': 'similique aut quo', 'userId': 9},
 {'completed': True,
  'id': 175,
  'title': 'laudantium eius officia perferendis provident perspiciatis '
           'asperiores',
  'userId': 9},
 {'completed': False,
  'id': 176,
  'title': 'magni soluta corrupti ut maiores rem quidem',
  'userId': 9},
 {'completed': False,
  'id': 177,
  'title': 'et placeat temporibus voluptas est tempora quos quibusdam',
  'userId': 9},
 {'completed': True,
  'id': 178,
  'title': 'nesciunt itaque commodi tempore',
  'userId': 9},
 {'completed': True,
  'id': 179,
  'title': 'omnis consequuntur cupiditate impedit itaque ipsam quo',
  'userId': 9},
 {'completed': True,
  'id': 180,
  'title': 'debitis nisi et dolorem repellat et',
  'userId': 9},
 {'completed': False,
  'id': 181,
  'title': 'ut cupiditate sequi aliquam fuga maiores',
  'userId': 10},
 {'completed': True,
  'id': 182,
  'title': 'inventore saepe cumque et aut illum enim',
  'userId': 10},
 {'completed': True,
  'id': 183,
  'title': 'omnis nulla eum aliquam distinctio',
  'userId': 10},
 {'completed': False,
  'id': 184,
  'title': 'molestias modi perferendis perspiciatis',
  'userId': 10},
 {'completed': False,
  'id': 185,
  'title': 'voluptates dignissimos sed doloribus animi quaerat aut',
  'userId': 10},
 {'completed': False,
  'id': 186,
  'title': 'explicabo odio est et',
  'userId': 10},
 {'completed': False,
  'id': 187,
  'title': 'consequuntur animi possimus',
  'userId': 10},
 {'completed': True, 'id': 188, 'title': 'vel non beatae est', 'userId': 10},

### 2. Mostra per pantalla:

- La quantitat total de cada recurs.
- El codi d'estat de cada petició.

In [7]:
print(f'Quantitat de posts: {len(posts)}')
print(f'Quantitat de users: {len(users)}')
print(f'Quantitat de todos: {len(todos)}')

Quantitat de posts: 100
Quantitat de users: 10
Quantitat de todos: 200

In [8]:
print(f"Codi d'estat de posts: {posts_status}")
print(f"Codi d'estat de users: {users_status}")
print(f"Codi d'estat de todos: {todos_status}")

Codi d'estat de posts: 200
Codi d'estat de users: 200
Codi d'estat de todos: 200

### 3. Fes una petició a una publicació inexistent per obtenir un error 404 i mostra el codi d'estat rebut.

In [9]:
requests.post("https://jsonplaceholder.typicode.com", data={"key": "value"})

### 4. Fes una petició POST per crear una nova publicació fictícia. Inclou el títol, el cos del missatge i un userId.

- Mostra la resposta JSON.
- Mostra el codi d'estat.

In [10]:
url = "https://jsonplaceholder.typicode.com/posts"
              
data={
    'body': 'hola, em dic Sabina',
    'title': 'hola',
    'userId': 56
}

response = requests.post(url, json=data)
print(f"Codi d'estat: {response.status_code}\n")
print(f"Resposta JSON:\n{response.json()}")

Codi d'estat: 201

Resposta JSON:
{'body': 'hola, em dic Sabina', 'title': 'hola', 'userId': 56, 'id': 101}

### 5. Fes una petició PATCH per modificar parcialment una publicació existent.

- Mostra la resposta JSON.
- Mostra el codi d'estat.

In [11]:
url = "https://jsonplaceholder.typicode.com/posts/101"
              
data={
    'body': 'ADEU',
}

response = requests.patch(url, json=data)
print(f"Codi d'estat: {response.status_code}\n")
print(f"Resposta JSON:\n{response.json()}")

Codi d'estat: 200

Resposta JSON:
{'body': 'ADEU'}

In [12]:
# Consultar posts del dataset original
url = "https://jsonplaceholder.typicode.com/posts/101"

response = requests.get(url)
print(f"\nGET status: {response.status_code}")
print(response.json())

GET status: 404
{}

El teu GET final no quadra perquè:

JSONPlaceholder no desa els canvis
el POST et retorna una simulació, no una inserció real

JSONPlaceholder només té posts del 1 al 100
el 101 no existeix realment
el PATCH no crea ni desa res
⚠️ Punt important

👉 PATCH no crea recursos
Només modifica si existeixen

En una API real:

PATCH /posts/101 → ❌ error si no existeix
GET /posts/101 → ❌ 404

Però JSONPlaceholder:

et deixa fer-ho igualment (mock)

In [13]:
# Consultar posts que existeixen a JSONPlaceholder
url = "https://jsonplaceholder.typicode.com/posts/97"

response = requests.get(url)
print(f"\nGET status: {response.status_code}")
print(response.json())

GET status: 200
{'userId': 10, 'id': 97, 'title': 'quas fugiat ut perspiciatis vero provident', 'body': 'eum non blanditiis soluta porro quibusdam voluptas\nvel voluptatem qui placeat dolores qui velit aut\nvel inventore aut cumque culpa explicabo aliquid at\nperspiciatis est et voluptatem dignissimos dolor itaque sit nam'}

### 6. Fes una petició DELETE sobre una publicació.

- Mostra la resposta JSON.
- Mostra el codi d'estat.

In [14]:
url = "https://jsonplaceholder.typicode.com/posts/97"

response = requests.delete(url)
print(f"DELETE status: {response.status_code}")
print(response.json())

DELETE status: 200
{}

## Nivell 2

Interacció amb una [API pública real](https://github.com/public-apis/public-apis)

### 1. Explora el repositori de Public APIs i tria una API que permeti fer peticions GET.

https://api.fda.gov/
https://open.fda.gov/apis/try-the-api/

### 2. Llegeix la documentació de l'API:

Revisa la secció d’endpoints disponibles. En un markdown, apunta com a mínim dos endpoints diferents.
Comprova si ofereix filtres o paràmetres opcionals interessants. En un markdown, anota’ls.
Verifica que la resposta sigui en format JSON (és el més adequat per a aquest exercici).

**Endpoints**:

- Animal & Veterinary API Endpoints
- *Drug API Endpoints*
    - Adverse events
    - Drug shortage
- Device API Endpoints
- Food API Endpoints
- Cosmetic API Endpoints
- Other API Endpoints
- Tobacco API Endpoints
- Transparency API Endpoints

From construct the query [documentation](https://open.fda.gov/apis/query-parameters/):

**Query parameters**
The API supports five query parameters. The basic building block of queries is the search parameter. Use it to “filter” requests to the API by looking in specific fields for matches. Each endpoint has its own unique fields that can be searched.

- search: What to search for, in which fields. If you don’t specify a field to search, the API will search in every field.
- sort: Sort the results of the search by the specified field in ascending or descending order by using the :asc or :desc modifier.
- count: Count the number of unique values of a certain field, for all the records that matched the search parameter. By default, the API returns the 1000 most frequent values.
- limit: Return up to this number of records that match the search parameter. Currently, the largest allowed value for the limit parameter is 1000.
- skip: Skip this number of records that match the search parameter, then return the matching records that follow. Use in combination with limit to paginate results.
Currently, the largest allowed value for the skip parameter is 25000. See Paging if you require paging through larger result sets.

### 3. Fes una petició GET senzilla:

Mostra el codi d'estat de la resposta.
Imprimeix de forma clara alguns dels camps de la resposta JSON.

In [15]:
response = requests.get("https://api.fda.gov/drug/event.json")
print(f"\nGET status: {response.status_code}")
pp.pprint(response.json())

GET status: 200
{'meta': {'disclaimer': 'Do not rely on openFDA to make decisions regarding '
                        'medical care. While we make every effort to ensure '
                        'that data is accurate, you should assume all results '
                        'are unvalidated. We may limit or otherwise restrict '
                        'your access to the API in line with our Terms of '
                        'Service.',
          'last_updated': '2026-01-27',
          'license': 'https://open.fda.gov/license/',
          'results': {'limit': 1, 'skip': 0, 'total': 20006989},
          'terms': 'https://open.fda.gov/terms/'},
 'results': [{'companynumb': 'JACAN16471',
              'fulfillexpeditecriteria': '1',
              'patient': {'drug': [{'drugadministrationroute': '041',
                                    'drugauthorizationnumb': '019813',
                                    'drugcharacterization': '1',
                                    'drugindication': 'DRUG ABUSE',
                                    'medicinalproduct': 'DURAGESIC-100'}],
                          'patientdeath': {'patientdeathdate': None,
                                           'patientdeathdateformat': None},
                          'patientonsetage': '26',
                          'patientonsetageunit': '801',
                          'patientsex': '1',
                          'reaction': [{'reactionmeddrapt': 'DRUG '
                                                            'ADMINISTRATION '
                                                            'ERROR'},
                                       {'reactionmeddrapt': 'OVERDOSE'}]},
              'primarysource': {'qualification': '3',
                                'reportercountry': 'CANADA'},
              'receiptdate': '20080625',
              'receiptdateformat': '102',
              'receivedate': '20080707',
              'receivedateformat': '102',
              'receiver': None,
              'safetyreportid': '5801206-7',
              'sender': {'senderorganization': 'FDA-Public Use'},
              'serious': '1',
              'seriousnessdeath': '1',
              'transmissiondate': '20090109',
              'transmissiondateformat': '102'}]}

In [16]:
response = requests.get('https://api.fda.gov/drug/event.json?search=occurcountry:"US"&sort=transmissiondate:desc&limit=3')
print(f"\nGET status: {response.status_code}")
pp.pprint(response.json())

# search=occurcountry:"Spain"&sort=transmissiondate:desc&limit=10

GET status: 200
{'meta': {'disclaimer': 'Do not rely on openFDA to make decisions regarding '
                        'medical care. While we make every effort to ensure '
                        'that data is accurate, you should assume all results '
                        'are unvalidated. We may limit or otherwise restrict '
                        'your access to the API in line with our Terms of '
                        'Service.',
          'last_updated': '2026-01-27',
          'license': 'https://open.fda.gov/license/',
          'results': {'limit': 3, 'skip': 0, 'total': 11405722},
          'terms': 'https://open.fda.gov/terms/'},
 'results': [{'companynumb': 'PHEH2016US017461',
              'fulfillexpeditecriteria': '2',
              'occurcountry': 'US',
              'patient': {'drug': [{'actiondrug': '1',
                                    'activesubstance': {'activesubstancename': 'SECUKINUMAB'},
                                    'drugadministrationroute': '050',
                                    'drugauthorizationnumb': '125504',
                                    'drugcharacterization': '1',
                                    'drugdosageform': 'Solution for injection',
                                    'drugdosagetext': '300 MG, QMO',
                                    'drugenddate': '20160523',
                                    'drugenddateformat': '102',
                                    'drugindication': 'Psoriasis',
                                    'drugintervaldosagedefinition': '802',
                                    'drugintervaldosageunitnumb': '1',
                                    'drugseparatedosagenumb': '1',
                                    'drugstartdate': '20151102',
                                    'drugstartdateformat': '102',
                                    'drugstructuredosagenumb': '300',
                                    'drugstructuredosageunit': '003',
                                    'drugtreatmentduration': '204',
                                    'drugtreatmentdurationunit': '804',
                                    'medicinalproduct': 'COSENTYX',
                                    'openfda': {'application_number': ['BLA125504',
                                                                       'BLA761349'],
                                                'brand_name': ['COSENTYX'],
                                                'generic_name': ['SECUKINUMAB'],
                                                'manufacturer_name': ['Novartis '
                                                                      'Pharmaceuticals '
                                                                      'Corporation'],
                                                'nui': ['N0000191495',
                                                        'N0000191494'],
                                                'package_ndc': ['0078-0639-41',
                                                                '0078-0639-68',
                                                                '0078-0639-98',
                                                                '0078-0639-97',
                                                                '0078-1056-97',
                                                                '0078-1056-99',
                                                                '0078-1070-68',
                                                                '0078-1070-96',
                                                                '0078-1168-61'],
                                                'pharm_class_epc': ['Interleukin-17A '
                                                                    'Antagonist '
                                                                    '[EPC]'],
                                                'pharm_class_moa': ['Interleukin-17A '
                                                                    'Antagonists '
                                                                    '[MoA]'],
                                                'product_ndc': ['0078-0639',
                                                                '0078-1056',
                                                                '0078-1070',
                                                                '0078-1168'],
                                                'product_type': ['HUMAN '
                                                                 'PRESCRIPTION '
                                                                 'DRUG'],
                                                'route': ['SUBCUTANEOUS',
                                                          'INTRAVENOUS'],
                                                'rxcui': ['1599792',
                                                          '1599797',
                                                          '1653241',
                                                          '1653243',
                                                          '2550712',
                                                          '2550713',
                                                          '2637347',
                                                          '2637348',
                                                          '2667419',
                                                          '2667423'],
                                                'spl_id': ['f3e35b01-17a4-4ca7-8667-4447e80c29a5'],
                                                'spl_set_id': ['77c4b13e-7df3-42d4-81db-3d0cddb7f67a'],
                                                'substance_name': ['SECUKINUMAB'],
                                                'unii': ['DLG4EML025']}},
                                   {'actiondrug': '5',
                                    'activesubstance': {'activesubstancename': 'ASPIRIN'},
                                    'drugadditional': '3',
                                    'drugadministrationroute': '065',
                                    'drugcharacterization': '2',
                                    'drugdosagetext': 'UNK',
                                    'drugindication': 'Product used for '
                                                      'unknown indication',
                                    'medicinalproduct': 'ASPIRIN',
                                    'openfda': {'application_number': ['M013',
                                                                       'M013.50',
                                                                       'part343',
                                                                       'M'],
                                                'brand_name': ['BAYER GENUINE '
                                                               'ASPIRIN',
                                                               'ASPIRIN',
                                                               'ENTERIC '
                                                               'ASPIRIN',
                                                               'ADULT LOW DOSE '
                                                               'ASPIRIN',
                                                               'CHEWABLE '
                                                               'ASPIRIN',
                                                               'DRUG MART '
                                                               'EFFERVESCENT '
                                                               'PAIN RELIEF',
                                                               'ASPIRIN LOW '
                                                               'DOSE',
                                                               'ASPIRIN '
                                                               'ENTERIC COATED',
                                                               'ASPIRIN 81',
                                                               'ADULT CHEWABLE '
                                                               'ASPIRIN',
                                                               'ASPIRIN 81MG',
                                                               'ADULT LOW DOSE '
                                                               'ENTERIC COATED '
                                                               'ASPIRIN',
                                                               'EXTRA STRENGTH '
                                                               'ASPIRIN 325 MG',
                                                               'ASPIRIN LOW '
                                                               'DOSE SAFETY '
                                                               'COATED',
                                                               'GERITREX '
                                                               'ASPIRIN',
                                                               'BUFFERED '
                                                               'ASPIRIN',
                                                               'ENTERIC COATED '
                                                               'ASPIRIN',
                                                               'BUFFERIN '
                                                               'REGULAR '
                                                               'STRENGTH PAIN '
                                                               'RELIEF',
                                                               'EQUATE ASPIRIN',
                                                               'LOW DOSE '
                                                               'ASPIRIN',
                                                               'HEB '
                                                               'EFFERVESCENT '
                                                               'PAIN RELIEF',
                                                               'PAIN RELIEF '
                                                               'ASPIRIN LOW '
                                                               'DOSE',
                                                               'ASPIRIN 81 MG '
                                                               'LOW DOSE',
                                                               'ASPIRIN EXTRA '
                                                               'STRENGTH',
                                                               'BAYER CHEWABLE '
                                                               '- ASPIRIN '
                                                               'REGIMEN LOW '
                                                               'DOSE ASPIRIN '
                                                               'CHERRY '
                                                               'FLAVORED',
                                                               'TRAVEL SAVVY '
                                                               'ASPIRIN',
                                                               'CHEWABLE '
                                                               'ASPIRIN 81 MG',
                                                               'TOPCARE '
                                                               'ASPIRIN',
                                                               'RAPIDOL '
                                                               'ASPIRIN',
                                                               'CAREALL '
                                                               'ASPIRIN',
                                                               'ASPIRIN '
                                                               'REGULAR '
                                                               'STRENGTH',
                                                               'REGULAR '
                                                               'STRENGTH '
                                                               'ASPIRIN',
                                                               'LOW DOSE '
                                                               'MINIPRIN '
                                                               'ENTERIC SAFETY '
                                                               'COATED',
                                                               'ASPIRIN '
                                                               'DELAYED '
                                                               'RELEASE',
                                                               'GOOD NEIGHBOR '
                                                               'PHARMACY '
                                                               'ASPIRIN',
                                                               'ADULT LOW DOSE '
                                                               'ASPIRIN 81 MG',
                                                               'LEADER ASPIRIN',
                                                               'CHEWABLE LOW '
                                                               'DOSE ASPIRIN',
                                                               'CIRCLE K '
                                                               'ASPIRIN 325',
                                                               'LOW DOSE '
                                                               'ASPIRIN '
                                                               'ENTERIC SAFETY '
                                                               'COATED',
                                                               'ASPIRIN 81MG '
                                                               'ENTERIC COATED',
                                                               'CHILDRENS '
                                                               'ASPIRIN',
                                                               'CVS '
                                                               'EFFERVESCENT '
                                                               'PAIN RELIEVER',
                                                               'BASIC CARE '
                                                               'ASPIRIN',
                                                               'SIGNATURE '
                                                               'SELECT '
                                                               'EFFERVESCENT '
                                                               'PAIN RELIEF',
                                                               'TRI-BUFFERED '
                                                               'ASPIRIN',
                                                               'ASPIRIN '
                                                               'ENTERIC '
                                                               'COATED, '
                                                               'REGULAR '
                                                               'STRENGTH',
                                                               'ASPIRIN LOW '
                                                               'DOSE CHEWABLE',
                                                               'ASPIRIN '
                                                               'ENTERIC SAFETY '
                                                               'COATED',
                                                               'MEDIQUE AT '
                                                               'HOME ASPIRIN',
                                                               'REGULAR '
                                                               'STRENGTH '
                                                               'ENTERIC COATED '
                                                               'ASPIRIN',
                                                               'DYE-FREE '
                                                               'ASPIRIN 81',
                                                               'PUBLIX FAST '
                                                               'RELIEF '
                                                               'EFFERVESCENT - '
                                                               'ORIGINAL '
                                                               'FLAVOR',
                                                               'BEST CHOICE '
                                                               'EFFERVESCENT '
                                                               'PAIN RELIEVER '
                                                               '36',
                                                               'ASPIRIN 81 MG',
                                                               'ASPIRIN 325 MG',
                                                               'BAYER ASPIRIN '
                                                               'ORIGINAL, '
                                                               'TRAVEL BASIX',
                                                               'BAYER ASPIRIN '
                                                               'ORIGINAL, CVP '
                                                               'HEALTH',
                                                               'BAYER',
                                                               'QUALITY CHOICE '
                                                               'EFFERVESCENT '
                                                               'PAIN RELIEF',
                                                               'ASPI-COR',
                                                               'UNISHIELD '
                                                               'ASPIRIN',
                                                               'FAMILY '
                                                               'WELLNESS PAIN '
                                                               'RELIEVER',
                                                               'ASPIRINA '
                                                               'CAPLETS',
                                                               'ASPIRIN 81MG '
                                                               'ENTERIC COATED '
                                                               'LOW STRENGTH '
                                                               'ASPIRIN '
                                                               'REGIMEN',
                                                               'EQUATE ASPIRIN '
                                                               'CHEWABLE',
                                                               'GOOD SENSE '
                                                               'ASPIRIN',
                                                               'BAYER ASPIRIN '
                                                               'REGIMEN '
                                                               'ENTERIC COATED',
                                                               'RUGBY ASPIRIN',
                                                               'ASPIRIN NSAID',
                                                               'RIGHT REMEDIES '
                                                               'LOW DOSE '

From [documentation](https://open.fda.gov/apis/drug/event/how-to-use-the-endpoint/) on how to use an endpoint:
Some key pointers
- An openFDA API query always begins with the base endpoint, which in this case is: https://api.fda.gov/drug/event.json
- Searches have a special syntax: search=field:term
- Unless otherwise specified, the API will return only one matching record for a search. You can specify the number of records to be returned by using the limit parameter. The maximum limit allowed is 1000 for any single API call. If no limit is set, the API will return one matching record.

In [17]:
url = 'https://api.fda.gov/drug/event.json?search=patient.drug.openfda.pharm_class_epc:"nonsteroidal+anti-inflammatory+drug"&count=patient.reaction.reactionmeddrapt.exact'

response = requests.get(url)
print(f"\nGET status: {response.status_code}")
pp.pprint(response.json())

GET status: 200
{'meta': {'disclaimer': 'Do not rely on openFDA to make decisions regarding '
                        'medical care. While we make every effort to ensure '
                        'that data is accurate, you should assume all results '
                        'are unvalidated. We may limit or otherwise restrict '
                        'your access to the API in line with our Terms of '
                        'Service.',
          'last_updated': '2026-01-27',
          'license': 'https://open.fda.gov/license/',
          'terms': 'https://open.fda.gov/terms/'},
 'results': [{'count': 92703, 'term': 'DRUG INEFFECTIVE'},
             {'count': 78915, 'term': 'FATIGUE'},
             {'count': 72007, 'term': 'NAUSEA'},
             {'count': 67689, 'term': 'PAIN'},
             {'count': 59621, 'term': 'HEADACHE'},
             {'count': 58799, 'term': 'DIARRHOEA'},
             {'count': 58618, 'term': 'DYSPNOEA'},
             {'count': 58470, 'term': 'OFF LABEL USE'},
             {'count': 51759, 'term': 'ARTHRALGIA'},
             {'count': 49715, 'term': 'DIZZINESS'},
             {'count': 47134, 'term': 'VOMITING'},
             {'count': 39995, 'term': 'RASH'},
             {'count': 39275, 'term': 'ASTHENIA'},
             {'count': 37255, 'term': 'MALAISE'},
             {'count': 36759, 'term': 'FALL'},
             {'count': 35532, 'term': 'PYREXIA'},
             {'count': 35170, 'term': 'PRURITUS'},
             {'count': 35079, 'term': 'PAIN IN EXTREMITY'},
             {'count': 34365, 'term': 'PNEUMONIA'},
             {'count': 31013, 'term': 'CONDITION AGGRAVATED'},
             {'count': 30012, 'term': 'DEATH'},
             {'count': 29041, 'term': 'WEIGHT DECREASED'},
             {'count': 28729, 'term': 'COUGH'},
             {'count': 28584, 'term': 'BACK PAIN'},
             {'count': 27838, 'term': 'DRUG HYPERSENSITIVITY'},
             {'count': 27284, 'term': 'HYPERTENSION'},
             {'count': 26704, 'term': 'INSOMNIA'},
             {'count': 26059, 'term': 'ANXIETY'},
             {'count': 25542, 'term': 'ACUTE KIDNEY INJURY'},
             {'count': 25158, 'term': 'MYOCARDIAL INFARCTION'},
             {'count': 25042, 'term': 'CHEST PAIN'},
             {'count': 25025, 'term': 'ABDOMINAL PAIN'},
             {'count': 24621, 'term': 'ABDOMINAL PAIN UPPER'},
             {'count': 23526, 'term': 'RHEUMATOID ARTHRITIS'},
             {'count': 23243, 'term': 'ABDOMINAL DISCOMFORT'},
             {'count': 23142, 'term': 'HYPOTENSION'},
             {'count': 23060, 'term': 'CONSTIPATION'},
             {'count': 23057, 'term': 'TOXICITY TO VARIOUS AGENTS'},
             {'count': 22867, 'term': 'PRODUCT USE IN UNAPPROVED INDICATION'},
             {'count': 22721, 'term': 'WEIGHT INCREASED'},
             {'count': 22542, 'term': 'JOINT SWELLING'},
             {'count': 22404, 'term': 'DEPRESSION'},
             {'count': 22391, 'term': 'DECREASED APPETITE'},
             {'count': 22276, 'term': 'NASOPHARYNGITIS'},
             {'count': 21890, 'term': 'PERIPHERAL SWELLING'},
             {'count': 21695, 'term': 'ANAEMIA'},
             {'count': 20912, 'term': 'GAIT DISTURBANCE'},
             {'count': 20836, 'term': 'HYPERSENSITIVITY'},
             {'count': 19731, 'term': 'CONFUSIONAL STATE'},
             {'count': 19372, 'term': 'BLOOD PRESSURE INCREASED'},
             {'count': 19342, 'term': 'FEELING ABNORMAL'},
             {'count': 19229, 'term': 'GASTROINTESTINAL HAEMORRHAGE'},
             {'count': 19226, 'term': 'SOMNOLENCE'},
             {'count': 18749, 'term': 'CEREBROVASCULAR ACCIDENT'},
             {'count': 18738, 'term': 'URINARY TRACT INFECTION'},
             {'count': 18644, 'term': 'DRUG INTERACTION'},
             {'count': 18267, 'term': 'MUSCLE SPASMS'},
             {'count': 18123, 'term': 'RENAL FAILURE'},
             {'count': 18078, 'term': 'HYPOAESTHESIA'},
             {'count': 18034, 'term': 'ALOPECIA'},
             {'count': 17521, 'term': 'URTICARIA'},
             {'count': 17315, 'term': 'PARAESTHESIA'},
             {'count': 17077, 'term': 'SINUSITIS'},
             {'count': 16633, 'term': 'FLUSHING'},
             {'count': 16477, 'term': 'MYALGIA'},
             {'count': 16441, 'term': 'ERYTHEMA'},
             {'count': 16367, 'term': 'INFECTION'},
             {'count': 16326, 'term': 'OVERDOSE'},
             {'count': 16281, 'term': 'OEDEMA PERIPHERAL'},
             {'count': 16272, 'term': 'DRUG INTOLERANCE'},
             {'count': 16038, 'term': 'PRODUCT USE ISSUE'},
             {'count': 16020, 'term': 'CHRONIC KIDNEY DISEASE'},
             {'count': 15616, 'term': 'MUSCULOSKELETAL STIFFNESS'},
             {'count': 15237, 'term': 'SWELLING'},
             {'count': 14801, 'term': 'GENERAL PHYSICAL HEALTH DETERIORATION'},
             {'count': 14741, 'term': 'COVID-19'},
             {'count': 14574, 'term': 'INFUSION RELATED REACTION'},
             {'count': 14233, 'term': 'CONTUSION'},
             {'count': 13950, 'term': 'DEHYDRATION'},
             {'count': 13945, 'term': 'PRODUCT DOSE OMISSION ISSUE'},
             {'count': 13881, 'term': 'MUSCULAR WEAKNESS'},
             {'count': 13614, 'term': 'HYPERHIDROSIS'},
             {'count': 13536, 'term': 'TREMOR'},
             {'count': 13358, 'term': 'ARTHROPATHY'},
             {'count': 13016, 'term': 'DYSPEPSIA'},
             {'count': 12760, 'term': 'HAEMOGLOBIN DECREASED'},
             {'count': 12626, 'term': 'COMPLETED SUICIDE'},
             {'count': 12596, 'term': 'INTENTIONAL PRODUCT USE ISSUE'},
             {'count': 12510, 'term': 'MEMORY IMPAIRMENT'},
             {'count': 12343, 'term': 'ARTHRITIS'},
             {'count': 12218, 'term': 'ATRIAL FIBRILLATION'},
             {'count': 12067, 'term': 'HEPATIC ENZYME INCREASED'},
             {'count': 11946, 'term': 'GASTROOESOPHAGEAL REFLUX DISEASE'},
             {'count': 11645, 'term': 'BLOOD GLUCOSE INCREASED'},
             {'count': 11576, 'term': 'LOSS OF CONSCIOUSNESS'},
             {'count': 11572, 'term': 'CHILLS'},
             {'count': 11492, 'term': 'INJECTION SITE PAIN'},
             {'count': 11406,
              'term': 'INAPPROPRIATE SCHEDULE OF PRODUCT ADMINISTRATION'},
             {'count': 11315, 'term': 'INCORRECT DOSE ADMINISTERED'},
             {'count': 11087, 'term': 'GASTROINTESTINAL DISORDER'}]}

### 4. Converteix les dades a un DataFrame de pandas:

Mostra les primeres files del DataFrame.

In [18]:
data = dict(response.json())

In [19]:
data.keys()

dict_keys(['meta', 'results'])

In [20]:
results= data['results']
results

[{'term': 'DRUG INEFFECTIVE', 'count': 92703},
 {'term': 'FATIGUE', 'count': 78915},
 {'term': 'NAUSEA', 'count': 72007},
 {'term': 'PAIN', 'count': 67689},
 {'term': 'HEADACHE', 'count': 59621},
 {'term': 'DIARRHOEA', 'count': 58799},
 {'term': 'DYSPNOEA', 'count': 58618},
 {'term': 'OFF LABEL USE', 'count': 58470},
 {'term': 'ARTHRALGIA', 'count': 51759},
 {'term': 'DIZZINESS', 'count': 49715},
 {'term': 'VOMITING', 'count': 47134},
 {'term': 'RASH', 'count': 39995},
 {'term': 'ASTHENIA', 'count': 39275},
 {'term': 'MALAISE', 'count': 37255},
 {'term': 'FALL', 'count': 36759},
 {'term': 'PYREXIA', 'count': 35532},
 {'term': 'PRURITUS', 'count': 35170},
 {'term': 'PAIN IN EXTREMITY', 'count': 35079},
 {'term': 'PNEUMONIA', 'count': 34365},
 {'term': 'CONDITION AGGRAVATED', 'count': 31013},
 {'term': 'DEATH', 'count': 30012},
 {'term': 'WEIGHT DECREASED', 'count': 29041},
 {'term': 'COUGH', 'count': 28729},
 {'term': 'BACK PAIN', 'count': 28584},
 {'term': 'DRUG HYPERSENSITIVITY', 'count': 27838},
 {'term': 'HYPERTENSION', 'count': 27284},
 {'term': 'INSOMNIA', 'count': 26704},
 {'term': 'ANXIETY', 'count': 26059},
 {'term': 'ACUTE KIDNEY INJURY', 'count': 25542},
 {'term': 'MYOCARDIAL INFARCTION', 'count': 25158},
 {'term': 'CHEST PAIN', 'count': 25042},
 {'term': 'ABDOMINAL PAIN', 'count': 25025},
 {'term': 'ABDOMINAL PAIN UPPER', 'count': 24621},
 {'term': 'RHEUMATOID ARTHRITIS', 'count': 23526},
 {'term': 'ABDOMINAL DISCOMFORT', 'count': 23243},
 {'term': 'HYPOTENSION', 'count': 23142},
 {'term': 'CONSTIPATION', 'count': 23060},
 {'term': 'TOXICITY TO VARIOUS AGENTS', 'count': 23057},
 {'term': 'PRODUCT USE IN UNAPPROVED INDICATION', 'count': 22867},
 {'term': 'WEIGHT INCREASED', 'count': 22721},
 {'term': 'JOINT SWELLING', 'count': 22542},
 {'term': 'DEPRESSION', 'count': 22404},
 {'term': 'DECREASED APPETITE', 'count': 22391},
 {'term': 'NASOPHARYNGITIS', 'count': 22276},
 {'term': 'PERIPHERAL SWELLING', 'count': 21890},
 {'term': 'ANAEMIA', 'count': 21695},
 {'term': 'GAIT DISTURBANCE', 'count': 20912},
 {'term': 'HYPERSENSITIVITY', 'count': 20836},
 {'term': 'CONFUSIONAL STATE', 'count': 19731},
 {'term': 'BLOOD PRESSURE INCREASED', 'count': 19372},
 {'term': 'FEELING ABNORMAL', 'count': 19342},
 {'term': 'GASTROINTESTINAL HAEMORRHAGE', 'count': 19229},
 {'term': 'SOMNOLENCE', 'count': 19226},
 {'term': 'CEREBROVASCULAR ACCIDENT', 'count': 18749},
 {'term': 'URINARY TRACT INFECTION', 'count': 18738},
 {'term': 'DRUG INTERACTION', 'count': 18644},
 {'term': 'MUSCLE SPASMS', 'count': 18267},
 {'term': 'RENAL FAILURE', 'count': 18123},
 {'term': 'HYPOAESTHESIA', 'count': 18078},
 {'term': 'ALOPECIA', 'count': 18034},
 {'term': 'URTICARIA', 'count': 17521},
 {'term': 'PARAESTHESIA', 'count': 17315},
 {'term': 'SINUSITIS', 'count': 17077},
 {'term': 'FLUSHING', 'count': 16633},
 {'term': 'MYALGIA', 'count': 16477},
 {'term': 'ERYTHEMA', 'count': 16441},
 {'term': 'INFECTION', 'count': 16367},
 {'term': 'OVERDOSE', 'count': 16326},
 {'term': 'OEDEMA PERIPHERAL', 'count': 16281},
 {'term': 'DRUG INTOLERANCE', 'count': 16272},
 {'term': 'PRODUCT USE ISSUE', 'count': 16038},
 {'term': 'CHRONIC KIDNEY DISEASE', 'count': 16020},
 {'term': 'MUSCULOSKELETAL STIFFNESS', 'count': 15616},
 {'term': 'SWELLING', 'count': 15237},
 {'term': 'GENERAL PHYSICAL HEALTH DETERIORATION', 'count': 14801},
 {'term': 'COVID-19', 'count': 14741},
 {'term': 'INFUSION RELATED REACTION', 'count': 14574},
 {'term': 'CONTUSION', 'count': 14233},
 {'term': 'DEHYDRATION', 'count': 13950},
 {'term': 'PRODUCT DOSE OMISSION ISSUE', 'count': 13945},
 {'term': 'MUSCULAR WEAKNESS', 'count': 13881},
 {'term': 'HYPERHIDROSIS', 'count': 13614},
 {'term': 'TREMOR', 'count': 13536},
 {'term': 'ARTHROPATHY', 'count': 13358},
 {'term': 'DYSPEPSIA', 'count': 13016},
 {'term': 'HAEMOGLOBIN DECREASED', 'count': 12760},
 {'term': 'COMPLETED SUICIDE', 'count': 12626},
 {'term': 'INTENTIONAL PRODUCT USE ISSUE', 'count': 12596},
 {'term': 'MEMORY IMPAIRMENT', 'count': 12510},
 {'term': 'ARTHRITIS', 'count': 12343},
 {'term': 'ATRIAL FIBRILLATION', 'count': 12218},
 {'term': 'HEPATIC ENZYME INCREASED', 'count': 12067},
 {'term': 'GASTROOESOPHAGEAL REFLUX DISEASE', 'count': 11946},
 {'term': 'BLOOD GLUCOSE INCREASED', 'count': 11645},
 {'term': 'LOSS OF CONSCIOUSNESS', 'count': 11576},
 {'term': 'CHILLS', 'count': 11572},
 {'term': 'INJECTION SITE PAIN', 'count': 11492},
 {'term': 'INAPPROPRIATE SCHEDULE OF PRODUCT ADMINISTRATION', 'count': 11406},
 {'term': 'INCORRECT DOSE ADMINISTERED', 'count': 11315},
 {'term': 'GASTROINTESTINAL DISORDER', 'count': 11087}]

In [21]:
df = pd.json_normalize(results)
df

                                                term  count
0                                   DRUG INEFFECTIVE  92703
1                                            FATIGUE  78915
2                                             NAUSEA  72007
3                                               PAIN  67689
4                                           HEADACHE  59621
..                                               ...    ...
95                                            CHILLS  11572
96                               INJECTION SITE PAIN  11492
97  INAPPROPRIATE SCHEDULE OF PRODUCT ADMINISTRATION  11406
98                       INCORRECT DOSE ADMINISTERED  11315
99                         GASTROINTESTINAL DISORDER  11087

[100 rows x 2 columns]

## Nivell 3

[API d'Open Data Barcelona](https://opendata-ajuntament.barcelona.cat/ca/desenvolupadors#APIS)

### 1. Utilitza l’API d’Open Data BCN per:

Cercar un dataset del teu interès mitjançant package_search i package_show.

In [22]:
url = 'https://opendata-ajuntament.barcelona.cat/data/api/action/'
method = 'package_search'

response = requests.get(url+method)
print(f"\nGET status: {response.status_code}")

data = response.json()

first_dataset = data["result"]["results"][0]

pp.pprint(first_dataset)

GET status: 200
{'ODS_Colateral1_agenda_2030': 'N/A',
 'ODS_Colateral2_agenda_2030': 'N/A',
 'ODS_Principal_agenda_2030': 'ODS 11: Ciutats i comunitats sostenibles',
 'api': 'Yes',
 'author': 'Gerència Municipal',
 'author_email': None,
 'code': 'notaris_compravendes_trans_tip_us',
 'creator_user_id': '50d6b44b-a141-4dc6-b663-5deb4ab0dd63',
 'dades_alt_valor': 'No',
 'dataset_fields_description': '__NOTA:__ Els recursos dels darrers anys poden '
                               'estar subjectes a lleugeres revisions o '
                               'modificacions a causa de la naturalesa del '
                               'procés de digitalització de les escriptures '
                               'notarials. Si la dada és menor que 5, s’indica '
                               'com ‘’..’’',
 'decalatgeNum': '1',
 'department': 'Oficina Municipal de Dades',
 'extras': [{'key': '01.Any', 'value': 'Any'},
            {'key': '02.Mes', 'value': 'Mes'},
            {'key': '03.Codi_Districte',
             'value': 'Codi del districte. Més informació a __[Unitats '
                      'administratives de la ciutat de '
                      'Barcelona](https://opendata-ajuntament.barcelona.cat/data/ca/dataset/20170706-districtes-barris)__'},
            {'key': '04.Nom_Districte', 'value': 'Nom del districte'},
            {'key': '05.Codi_Barri',
             'value': 'Codi del barri. Més informació a __[Unitats '
                      'administratives de la ciutat de '
                      'Barcelona](https://opendata-ajuntament.barcelona.cat/data/ca/dataset/20170706-districtes-barris)__'},
            {'key': '06.Nom_Barri', 'value': 'Nom del barri'},
            {'key': '07.Tipologia_Us_Codi',
             'value': 'Codi de la tipologia d’ús de l’immoble'},
            {'key': '08.Tipologia_Us_Desc',
             'value': 'Tipologia d’ús de l’immoble'},
            {'key': '09.Nombre', 'value': 'Nombre de transmissions'}],
 'fecha_publicacion': '2026-03-25',
 'frequency': 'MENSUAL',
 'fuente': 'Registres notarials de les compravendes de propietats '
           'immobiliàries de Barcelona',
 'geolocation': 'No',
 'groups': [],
 'hide_url': 'No',
 'historical': 'Yes',
 'id': '6e4e0b32-3347-442b-94d6-3d734b928815',
 'isopen': True,
 'license_id': 'CC-BY-4.0',
 'license_title': 'Creative Commons Attribution 4.0',
 'license_url': 'https://creativecommons.org/licenses/by/4.0/',
 'load_type': 'link_intern_desde_font_interna',
 'long_format': 'Yes',
 'mar_od': 'Yes',
 'metadata_modified': '2026-03-25T07:06:41.950568',
 'name': 'notaris_compravendes_trans_tip_us',
 'notes': 'Number of real estate property sale transactions in the city of '
          'Barcelona, based on notarial records, by property use during the '
          'specified period. Only geolocated transactions are included.',
 'notes_translated': {'ca': 'Nombre de transmissions de compravenda de '
                            'propietats immobiliàries a la ciutat de '
                            'Barcelona, segons els registres notarials, per '
                            'tipologia d’ús de l’immoble durant el període '
                            'especificat. Només s’inclouen els valors amb '
                            'geolocalització assignada.',
                      'en': 'Number of real estate property sale transactions '
                            'in the city of Barcelona, based on notarial '
                            'records, by property use during the specified '
                            'period. Only geolocated transactions are '
                            'included.',
                      'es': 'Número de transmisiones de compraventa de '
                            'propiedades inmobiliarias en la ciudad de '
                            'Barcelona, según los registros notariales, por '
                            'tipo de uso de la propiedad durante el período '
                            'especificado. Solamente se incluyen los valores '
                            'con geolocalización asignada.'},
 'num_resources': 15,
 'num_tags': 17,
 'organization': {'approval_status': 'approved',
                  'code': 'habitatge',
                  'created': '2017-01-24T16:55:05.903441',
                  'description': 'Housing',
                  'description_translated': {'ca': 'Habitatge',
                                             'en': 'Housing',
                                             'es': 'Vivienda'},
                  'display_name': 'Habitatge',
                  'groups': [{'capacity': 'public', 'name': 'territori'}],
                  'id': 'db34b773-2143-4fe1-a713-fdc11e61e0f1',
                  'image_display_url': 'https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon-padro',
                  'image_url': 'bcn-icon-padro',
                  'is_organization': True,
                  'name': 'habitatge',
                  'num_followers': 0,
                  'package_count': 63,
                  'parent': {'approval_status': 'approved',
                             'code': 'territori',
                             'created': '2017-01-24T16:55:06.680852',
                             'description': 'Territory',
                             'description_translated': {'ca': 'Territori',
                                                        'en': 'Territory',
                                                        'es': 'Territorio'},
                             'display_name': 'Territori',
                             'groups': [],
                             'id': 'fdb223be-3adc-4145-be97-980bcfbdaa3b',
                             'image_display_url': 'https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon2-territori',
                             'image_url': 'bcn-icon2-territori',
                             'is_organization': True,
                             'name': 'territori',
                             'num_followers': 0,
                             'package_count': 0,
                             'revision_id': '948d611b-5bfd-4878-a817-3bbdd28bae22',
                             'state': 'active',
                             'title': 'Territory',
                             'title_translated': {'ca': 'Territori',
                                                  'en': 'Territory',
                                                  'es': 'Territorio'},
                             'type': 'organization'},
                  'revision_id': '12142cd7-f12c-4899-9e07-e440f4719552',
                  'state': 'active',
                  'tematica_nti': 'vivienda',
                  'title': 'Housing',
                  'title_translated': {'ca': 'Habitatge',
                                       'en': 'Housing',
                                       'es': 'Vivienda'},
                  'type': 'organization'},
 'owner_org': 'db34b773-2143-4fe1-a713-fdc11e61e0f1',
 'private': False,
 'relationships_as_object': [],
 'relationships_as_subject': [],
 'resources': [{'api_access_number': '0',
                'api_access_number_absolute': '0',
                'cache_last_updated': None,
                'cache_url': None,
                'created': '2026-03-20T08:43:08.067848',
                'datastore_active': True,
                'description': '',
                'downloads': '0',
                'downloads_absolute': '0',
                'format': 'CSV',
                'hash': '',
                'hide_url': 'No',
                'id': '0d292f7d-0ad6-431d-8a54-6e9ad9d47ac3',
                'last_modified': '2026-03-20T08:43:08.016081',
                'map_visualization_res': 'none',
                'mimetype': None,
                'mimetype_inner': None,
                'name': '2026_notaris_compravendes_trans_tip_us.csv',
                'package_id': '6e4e0b32-3347-442b-94d6-3d734b928815',
                'position': 0,
                'qa': "{'updated': '2026-04-23T02:08:10.398691', "
                      "'openness_score': 3, 'archival_timestamp': None, "
                      "'format': u'CSV', 'created': "
                      "'2026-03-21T02:10:16.110913', 'resource_timestamp': "
                      "None, 'openness_score_reason': u'This file had not been "
                      'downloaded at the time of scoring it. URL extension '
                      '"csv" relates to format "CSV" and receives score: 3.\'}',
                'resource_type': None,
                'revision_id': 'c9ad8326-b03c-46ed-a651-41ddcc4b6502',
                'size': '30091',
                'state': 'active',
                'token_provider': '',
                'token_required': 'No',
                'token_type': '',
                'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/6e4e0b32-3347-442b-94d6-3d734b928815/resource/0d292f7d-0ad6-431d-8a54-6e9ad9d47ac3/download',
                'url_type': 'upload'},
               {'api_access_number': '0',
                'api_access_number_absolute': '0',
                'cache_last_updated': None,
                'cache_url': None,
                'created': '2026-03-20T08:44:30.511115',
                'datastore_active': True,
                'description': '',
                'downloads': '0',
                'downloads_absolute': '0',
                'format': 'CSV',
                'hash': '',
                'hide_url': 'No',
                'id': '4b8c5cf6-56aa-4a64-b87f-6159a1272206',
                'last_modified': '2026-03-20T08:44:30.453652',
                'map_visualization_res': 'none',
                'mimetype': None,
                'mimetype_inner': None,
                'name': '2025_notaris_compravendes_trans_tip_us.csv',
                'package_id': '6e4e0b32-3347-442b-94d6-3d734b928815',
                'position': 1,
                'qa': "{'updated': '2026-04-23T02:08:10.409162', "
                      "'openness_score': 3, 'archival_timestamp': None, "
                      "'format': u'CSV', 'created': "
                      "'2026-03-21T02:10:16.133993', 'resource_timestamp': "
                      "None, 'openness_score_reason': u'This file had not been "
                      'downloaded at the time of scoring it. URL extension '
                      '"csv" relates to format "CSV" and receives score: 3.\'}',
                'resource_type': None,
                'revision_id': '4fe99561-848a-4722-9af2-71020a70594d',
                'size': '183297',
                'state': 'active',
                'token_provider': '',
                'token_required': 'No',
                'token_type': '',
                'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/6e4e0b32-3347-442b-94d6-3d734b928815/resource/4b8c5cf6-56aa-4a64-b87f-6159a1272206/download',
                'url_type': 'upload'},
               {'api_access_number': '0',
                'api_access_number_absolute': '0',
                'cache_last_updated': None,
                'cache_url': None,
                'created': '2026-03-20T08:45:52.901764',
                'datastore_active': True,
                'description': '',
                'downloads': '0',
                'downloads_absolute': '0',
                'format': 'CSV',
                'hash': '',
                'hide_url': 'No',
                'id': '8cef2abe-824f-48ea-8f2a-7cdb2689a6f8',
                'last_modified': '2026-03-20T08:45:52.840325',
                'map_visualization_res': 'none',
                'mimetype': None,
                'mimetype_inner': None,
                'name': '2024_notaris_compravendes_trans_tip_us.csv',
                'package_id': '6e4e0b32-3347-442b-94d6-3d734b928815',
                'position': 2,
                'qa': "{'updated': '2026-04-23T02:08:10.418741', "
                      "'openness_score': 3, 'archival_timestamp': None, "
                      "'format': u'CSV', 'created': "
                      "'2026-03-21T02:10:16.155368', 'resource_timestamp': "
                      "None, 'openness_score_reason': u'This file had not been "
                      'downloaded at the time of scoring it. URL extension '
                      '"csv" relates to format "CSV" and receives score: 3.\'}',
                'resource_type': None,
                'revision_id': '956167ce-da3e-4a8c-b0f3-7a8806a267ed',
                'size': '183299',
                'state': 'active',
                'token_provider': '',
                'token_required': 'No',
                'token_type': '',
                'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/6e4e0b32-3347-442b-94d6-3d734b928815/resource/8cef2abe-824f-48ea-8f2a-7cdb2689a6f8/download',
                'url_type': 'upload'},
               {'api_access_number': '0',
                'api_access_number_absolute': '0',
                'cache_last_updated': None,
                'cache_url': None,
                'created': '2026-03-20T08:47:15.395073',
                'datastore_active': True,
                'description': '',
                'downloads': '0',
                'downloads_absolute': '0',
                'format': 'CSV',
                'hash': '',
                'hide_url': 'No',
                'id': 'af3ad569-4f1e-4409-afb1-a760975a3519',
                'last_modified': '2026-03-20T08:47:15.321382',
                'map_visualization_res': 'none',
                'mimetype': None,
                'mimetype_inner': None,
                'name': '2023_notaris_compravendes_trans_tip_us.csv',
                'package_id': '6e4e0b32-3347-442b-94d6-3d734b928815',
                'position': 3,
                'qa': "{'updated': '2026-04-23T02:08:10.429883', "
                      "'openness_score': 3, 'archival_timestamp': None, "
                      "'format': u'CSV', 'created': "
                      "'2026-03-21T02:10:16.181436', 'resource_timestamp': "
                      "None, 'openness_score_reason': u'This file had not been "
                      'downloaded at the time of scoring it. URL extension '
                      '"csv" relates to format "CSV" and receives score: 3.\'}',
                'resource_type': None,
                'revision_id': '87b90996-0dcc-47a3-8b1e-5cf4c12f1b50',
                'size': '170946',
                'state': 'active',
                'token_provider': '',
                'token_required': 'No',
                'token_type': '',
                'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/6e4e0b32-3347-442b-94d6-3d734b928815/resource/af3ad569-4f1e-4409-afb1-a760975a3519/download',
                'url_type': 'upload'},
               {'api_access_number': '0',
                'api_access_number_absolute': '0',
                'cache_last_updated': None,
                'cache_url': None,
                'created': '2026-03-20T08:48:38.274750',
                'datastore_active': True,
                'description': '',
                'downloads': '0',
                'downloads_absolute': '0',
                'format': 'CSV',
                'hash': '',
                'hide_url': 'No',
                'id': '1e8e5128-94fe-4e9b-9a7e-edf5a28ff812',
                'last_modified': '2026-03-20T08:48:38.206484',
                'map_visualization_res': 'none',
                'mimetype': None,
                'mimetype_inner': None,
                'name': '2022_notaris_compravendes_trans_tip_us.csv',
                'package_id': '6e4e0b32-3347-442b-94d6-3d734b928815',
                'position': 4,
                'qa': "{'updated': '2026-04-23T02:08:10.443063', "
                      "'openness_score': 3, 'archival_timestamp': None, "
                      "'format': u'CSV', 'created': "
                      "'2026-03-21T02:10:16.201715', 'resource_timestamp': "
                      "None, 'openness_score_reason': u'This file had not been "
                      'downloaded at the time of scoring it. URL extension '
                      '"csv" relates to format "CSV" and receives score: 3.\'}',
                'resource_type': None,
                'revision_id': '2cdfcb85-bc8f-4b10-bdee-39ac25de29ea',
                'size': '181199',
                'state': 'active',
                'token_provider': '',
                'token_required': 'No',
                'token_type': '',
                'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/6e4e0b32-3347-442b-94d6-3d734b928815/resource/1e8e5128-94fe-4e9b-9a7e-edf5a28ff812/download',
                'url_type': 'upload'},
               {'api_access_number': '0',
                'api_access_number_absolute': '0',
                'cache_last_updated': None,
                'cache_url': None,
                'created': '2026-03-20T08:50:01.577100',
                'datastore_active': True,
                'description': '',
                'downloads': '0',
                'downloads_absolute': '0',
                'format': 'CSV',
                'hash': '',
                'hide_url': 'No',
                'id': 'e27e7dd8-b2c9-47ed-a43e-291e247b46a9',
                'last_modified': '2026-03-20T08:50:01.462210',
                'map_visualization_res': 'none',
                'mimetype': None,
                'mimetype_inner': None,
                'name': '2021_notaris_compravendes_trans_tip_us.csv',
                'package_id': '6e4e0b32-3347-442b-94d6-3d734b928815',
                'position': 5,
                'qa': "{'updated': '2026-04-23T02:08:10.455722', "
                      "'openness_score': 3, 'archival_timestamp': None, "
                      "'format': u'CSV', 'created': "
                      "'2026-03-21T02:10:16.225036', 'resource_timestamp': "
                      "None, 'openness_score_reason': u'This file had not been "
                      'downloaded at the time of scoring it. URL extension '
                      '"csv" relates to format "CSV" and receives score: 3.\'}',
                'resource_type': None,
                'revision_id': 'ee807567-6726-46ae-aeab-5ed36bba9db9',
                'size': '171125',
                'state': 'active',
                'token_provider': '',
                'token_required': 'No',
                'token_type': '',
                'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/6e4e0b32-3347-442b-94d6-3d734b928815/resource/e27e7dd8-b2c9-47ed-a43e-291e247b46a9/download',
                'url_type': 'upload'},
               {'api_access_number': '0',
                'api_access_number_absolute': '0',
                'cache_last_updated': None,
                'cache_url': None,
                'created': '2026-03-20T08:51:25.085684',
                'datastore_active': True,
                'description': '',
                'downloads': '0',
                'downloads_absolute': '0',
                'format': 'CSV',
                'hash': '',
                'hide_url': 'No',
                'id': '6ccd5b89-8ef7-46ed-9607-ee2b70ddc8de',
                'last_modified': '2026-03-20T08:51:24.920544',
                'map_visualization_res': 'none',
                'mimetype': None,
                'mimetype_inner': None,
                'name': '2020_notaris_compravendes_trans_tip_us.csv',
                'package_id': '6e4e0b32-3347-442b-94d6-3d734b928815',
                'position': 6,
                'qa': "{'updated': '2026-04-23T02:08:10.469898', "
                      "'openness_score': 3, 'archival_timestamp': None, "
                      "'format': u'CSV', 'created': "
                      "'2026-03-21T02:10:16.247999', 'resource_timestamp': "
                      "None, 'openness_score_reason': u'This file had not been "
                      'downloaded at the time of scoring it. URL extension '
                      '"csv" relates to format "CSV" and receives score: 3.\'}',
                'resource_type': None,

In [23]:
print(first_dataset.keys())

dict_keys(['notes_translated', 'geolocation', 'dades_alt_valor', 'url_tornada', 'dataset_fields_description', 'fuente', 'tag', 'private', 'num_tags', 'code', 'frequency', 'id', 'title_translated', 'metadata_modified', 'author', 'author_email', 'isopen', 'long_format', 'state', 'version', 'mar_od', 'relationships_as_object', 'department', 'creator_user_id', 'type', 'resources', 'token_required', 'decalatgeNum', 'tags', 'ODS_Principal_agenda_2030', 'fecha_publicacion', 'ODS_Colateral2_agenda_2030', 'ODS_Colateral1_agenda_2030', 'license_id', 'hide_url', 'relationships_as_subject', 'license_title', 'groups', 'num_resources', 'organization', 'name', 'url', 'notes', 'owner_org', 'load_type', 'api', 'license_url', 'historical', 'title', 'revision_id', 'extras'])

In [24]:
print(first_dataset["title"])

Number of real estate property transactions, based on notarial records, by property use

In [25]:
datasets = data["result"]["results"]

for d in datasets:
    print(d["title"])

print('----')
dataset_id = datasets[6]["id"]
print(datasets[6]["title"])

Number of real estate property transactions, based on notarial records, by property use
Area (m²) of real estate properties transmitted by sale transaction, based on notarials records, by property use
Fees excluding VAT from the public price register for waste collection (excluding large producers) of the Barcelona City Council
Receipts and quota of the register of the Vados Tax of the Barcelona City Council
Receipts and charges from the motor vehicle tax roll of the Barcelona City Council
Immigrants
Emigrants
Cancellations for undue inscription
Registrations by omission
Deaths
----
Emigrants

In [26]:
url = 'https://opendata-ajuntament.barcelona.cat/data/api/action/'
method = 'package_show'

params = {"id": dataset_id}

response = requests.get(url+method, params=params)
data = response.json()
print(f"\nGET status: {response.status_code}")
pp.pprint(data["result"])

GET status: 200
{'ODS_Colateral1_agenda_2030': 'N/A',
 'ODS_Colateral2_agenda_2030': 'N/A',
 'ODS_Principal_agenda_2030': 'ODS 16: Pau, justícia i institucions sòlides',
 'api': 'Yes',
 'author': 'Gerència Municipal',
 'author_email': None,
 'code': 'pad_emi_mdbas',
 'creator_user_id': '50d6b44b-a141-4dc6-b663-5deb4ab0dd63',
 'dataset_fields_description': 'Les dades dels fluxos padronals estan sotmeses '
                               'a rectificacions d’acord amb els registres '
                               'oficials.. Si la dada és menor que 5, s’indica '
                               'com ‘’..’’',
 'decalatgeNum': 'N/A',
 'department': 'Oficina Municipal de Dades',
 'extras': [{'key': '01.Any', 'value': 'Any del moviment'},
            {'key': '02.Codi_Districte',
             'value': 'Codi del districte . Més informació a __[Unitats '
                      'administratives de la ciutat de '
                      'Barcelona](https://opendata-ajuntament.barcelona.cat/data/ca/dataset/20170706-districtes-barris)__'},
            {'key': '03.Nom_Districte',
             'value': 'Nom del districte . Més informació a __[Unitats '
                      'administratives de la ciutat de '
                      'Barcelona](https://opendata-ajuntament.barcelona.cat/data/ca/dataset/20170706-districtes-barris)__'},
            {'key': '04.Codi_Barri',
             'value': 'Codi del barri . Més informació a __[Unitats '
                      'administratives de la ciutat de '
                      'Barcelona](https://opendata-ajuntament.barcelona.cat/data/ca/dataset/20170706-districtes-barris)__'},
            {'key': '05.Nom_Barri',
             'value': 'Nom del barri . Més informació a __[Unitats '
                      'administratives de la ciutat de '
                      'Barcelona](https://opendata-ajuntament.barcelona.cat/data/ca/dataset/20170706-districtes-barris)__'},
            {'key': '06.AEB',
             'value': 'Àrea estadística bàsica . Més informació a __[Unitats '
                      'administratives de la ciutat de '
                      'Barcelona](https://opendata-ajuntament.barcelona.cat/data/ca/dataset/20170706-districtes-barris)__'},
            {'key': '07.Seccio_Censal',
             'value': 'Secció censal . Més informació a __[Unitats '
                      'administratives de la ciutat de '
                      'Barcelona](https://opendata-ajuntament.barcelona.cat/data/ca/dataset/20170706-districtes-barris)__'},
            {'key': '08.Valor', 'value': 'Nombre de persones'}],
 'fecha_publicacion': '2025-07-23',
 'frequency': 'ANUAL',
 'fuente': 'Ajuntament de Barcelona. Oficina Municipal de Dades (OMD). Padró '
           "Municipal d'Habitants",
 'geolocation': 'No',
 'groups': [],
 'hide_url': 'No',
 'historical': 'Yes',
 'id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
 'isopen': True,
 'license_id': 'CC-BY-4.0',
 'license_title': 'Creative Commons Attribution 4.0',
 'license_url': 'https://creativecommons.org/licenses/by/4.0/',
 'load_type': 'link_intern_desde_font_interna',
 'long_format': 'Yes',
 'mar_od': 'No',
 'metadata_modified': '2025-07-23T09:29:59.708933',
 'name': 'pad_emi_mdbas',
 'notes': 'Number of emigrant people in Barcelona by year by the Municipal '
          'Register of Inhabitants',
 'notes_translated': {'ca': 'Nombre de persones emigrants a Barcelona per any '
                            "segons el Padró Municipal d'Habitants",
                      'en': 'Number of emigrant people in Barcelona by year by '
                            'the Municipal Register of Inhabitants',
                      'es': 'Número de emigrantes en Barcelona por año según '
                            'el Padrón Municipal de Habitantes'},
 'num_resources': 56,
 'num_tags': 30,
 'organization': {'approval_status': 'approved',
                  'created': '2017-01-24T16:55:07.584105',
                  'description': '',
                  'id': 'bec2fda0-7697-4c99-a635-5fd159334034',
                  'image_url': 'bcn-icon-oficines-especialitzades',
                  'is_organization': True,
                  'name': 'demografia',
                  'revision_id': '3fa957d0-b4a6-4ee1-b45a-f86051920bcc',
                  'state': 'active',
                  'title': 'Demografia',
                  'type': 'organization'},
 'owner_org': 'bec2fda0-7697-4c99-a635-5fd159334034',
 'private': False,
 'qa': {'openness_score': 3,
        'openness_score_reason': 'This file had not been downloaded at the '
                                 'time of scoring it. URL extension "csv" '
                                 'relates to format "CSV" and receives score: '
                                 '3.',
        'updated': '2026-04-23T02:08:57.311440'},
 'relationships_as_object': [],
 'relationships_as_subject': [],
 'resources': [{'api_access_number': 31,
                'api_access_number_absolute': 75,
                'cache_last_updated': None,
                'cache_url': None,
                'created': '2025-07-23T07:14:50.743098',
                'datastore_active': True,
                'description': '',
                'downloads': 98,
                'downloads_absolute': 115,
                'format': 'CSV',
                'hash': '',
                'hide_url': 'No',
                'id': '41964dc5-927b-4a09-bf5a-59ab8927ee0e',
                'last_modified': None,
                'map_visualization_res': 'none',
                'mimetype': None,
                'mimetype_inner': None,
                'name': '2024_pad_emi_mdbas.csv',
                'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
                'position': 0,
                'qa': {'archival_timestamp': None,
                       'created': '2025-07-24T02:10:38.425714',
                       'format': 'CSV',
                       'openness_score': 3,
                       'openness_score_reason': 'This file had not been '
                                                'downloaded at the time of '
                                                'scoring it. URL extension '
                                                '"csv" relates to format "CSV" '
                                                'and receives score: 3.',
                       'resource_timestamp': None,
                       'updated': '2026-04-23T02:08:56.646051'},
                'resource_type': None,
                'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
                'size': '56166',
                'state': 'active',
                'token_provider': '',
                'token_required': 'No',
                'token_type': '',
                'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/41964dc5-927b-4a09-bf5a-59ab8927ee0e/download',
                'url_type': None},
               {'api_access_number': 3,
                'api_access_number_absolute': 8,
                'cache_last_updated': None,
                'cache_url': None,
                'created': '2025-07-23T07:13:33.325762',
                'datastore_active': False,
                'description': '',
                'downloads': 35,
                'downloads_absolute': 42,
                'format': 'JSON',
                'hash': '',
                'hide_url': 'No',
                'id': 'c296814f-e1fe-4e1c-bd96-3cea6c0bb4d1',
                'last_modified': None,
                'map_visualization_res': 'none',
                'mimetype': None,
                'mimetype_inner': None,
                'name': '2024_pad_emi_mdbas.json',
                'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
                'position': 1,
                'qa': {'archival_timestamp': None,
                       'created': '2025-07-24T02:10:38.454985',
                       'format': 'JSON',
                       'openness_score': 3,
                       'openness_score_reason': 'This file had not been '
                                                'downloaded at the time of '
                                                'scoring it. URL extension '
                                                '"json" relates to format '
                                                '"JSON" and receives score: 3.',
                       'resource_timestamp': None,
                       'updated': '2026-04-23T02:08:56.656647'},
                'resource_type': None,
                'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
                'size': '164994',
                'state': 'active',
                'token_provider': '',
                'token_required': 'No',
                'token_type': '',
                'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/c296814f-e1fe-4e1c-bd96-3cea6c0bb4d1/download',
                'url_type': None},
               {'api_access_number': 7,
                'api_access_number_absolute': 7,
                'cache_last_updated': None,
                'cache_url': None,
                'created': '2025-07-23T07:12:15.328632',
                'datastore_active': True,
                'description': '',
                'downloads': 39,
                'downloads_absolute': 39,
                'format': 'CSV',
                'hash': '',
                'hide_url': 'No',
                'id': '4dced815-e9ae-445a-97f4-d4adb080d3db',
                'last_modified': None,
                'map_visualization_res': 'none',
                'mimetype': None,
                'mimetype_inner': None,
                'name': '2023_pad_emi_mdbas.csv',
                'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
                'position': 2,
                'qa': {'archival_timestamp': None,
                       'created': '2025-07-24T02:10:38.484592',
                       'format': 'CSV',
                       'openness_score': 3,
                       'openness_score_reason': 'This file had not been '
                                                'downloaded at the time of '
                                                'scoring it. URL extension '
                                                '"csv" relates to format "CSV" '
                                                'and receives score: 3.',
                       'resource_timestamp': None,
                       'updated': '2026-04-23T02:08:56.667279'},
                'resource_type': None,
                'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
                'size': '56158',
                'state': 'active',
                'token_provider': '',
                'token_required': 'No',
                'token_type': '',
                'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/4dced815-e9ae-445a-97f4-d4adb080d3db/download',
                'url_type': None},
               {'api_access_number': 0,
                'api_access_number_absolute': 0,
                'cache_last_updated': None,
                'cache_url': None,
                'created': '2025-07-23T07:10:57.785945',
                'datastore_active': False,
                'description': '',
                'downloads': 24,
                'downloads_absolute': 24,
                'format': 'JSON',
                'hash': '',
                'hide_url': 'No',
                'id': '15e6fdb8-dacd-49ec-81fb-a76902c0ca99',
                'last_modified': None,
                'map_visualization_res': 'none',
                'mimetype': None,
                'mimetype_inner': None,
                'name': '2023_pad_emi_mdbas.json',
                'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
                'position': 3,
                'qa': {'archival_timestamp': None,
                       'created': '2025-07-24T02:10:38.516511',
                       'format': 'JSON',
                       'openness_score': 3,
                       'openness_score_reason': 'This file had not been '
                                                'downloaded at the time of '
                                                'scoring it. URL extension '
                                                '"json" relates to format '
                                                '"JSON" and receives score: 3.',
                       'resource_timestamp': None,
                       'updated': '2026-04-23T02:08:56.679649'},
                'resource_type': None,
                'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
                'size': '164986',
                'state': 'active',
                'token_provider': '',
                'token_required': 'No',
                'token_type': '',
                'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/15e6fdb8-dacd-49ec-81fb-a76902c0ca99/download',
                'url_type': None},
               {'api_access_number': 7,
                'api_access_number_absolute': 7,
                'cache_last_updated': None,
                'cache_url': None,
                'created': '2025-07-23T07:09:40.082049',
                'datastore_active': True,
                'description': '',
                'downloads': 40,
                'downloads_absolute': 40,
                'format': 'CSV',
                'hash': '',
                'hide_url': 'No',
                'id': '44b948c5-adcb-4b19-8dd2-aea43769206e',
                'last_modified': None,
                'map_visualization_res': 'none',
                'mimetype': None,
                'mimetype_inner': None,
                'name': '2022_pad_emi_mdbas.csv',
                'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
                'position': 4,
                'qa': {'archival_timestamp': None,
                       'created': '2025-07-24T02:10:38.538914',
                       'format': 'CSV',
                       'openness_score': 3,
                       'openness_score_reason': 'This file had not been '
                                                'downloaded at the time of '
                                                'scoring it. URL extension '
                                                '"csv" relates to format "CSV" '
                                                'and receives score: 3.',
                       'resource_timestamp': None,
                       'updated': '2026-04-23T02:08:56.690733'},
                'resource_type': None,
                'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
                'size': '56154',
                'state': 'active',
                'token_provider': '',
                'token_required': 'No',
                'token_type': '',
                'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/44b948c5-adcb-4b19-8dd2-aea43769206e/download',
                'url_type': None},
               {'api_access_number': 0,
                'api_access_number_absolute': 0,
                'cache_last_updated': None,
                'cache_url': None,
                'created': '2025-07-23T07:08:22.935173',
                'datastore_active': False,
                'description': '',
                'downloads': 23,
                'downloads_absolute': 25,
                'format': 'JSON',
                'hash': '',
                'hide_url': 'No',
                'id': '78b9bac7-e20c-4611-bf56-ba8604d8648f',
                'last_modified': None,
                'map_visualization_res': 'none',
                'mimetype': None,
                'mimetype_inner': None,
                'name': '2022_pad_emi_mdbas.json',
                'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
                'position': 5,
                'qa': {'archival_timestamp': None,
                       'created': '2025-07-24T02:10:38.570988',
                       'format': 'JSON',
                       'openness_score': 3,
                       'openness_score_reason': 'This file had not been '
                                                'downloaded at the time of '
                                                'scoring it. URL extension '
                                                '"json" relates to format '
                                                '"JSON" and receives score: 3.',
                       'resource_timestamp': None,
                       'updated': '2026-04-23T02:08:56.704731'},
                'resource_type': None,
                'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
                'size': '164982',
                'state': 'active',
                'token_provider': '',
                'token_required': 'No',
                'token_type': '',
                'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/78b9bac7-e20c-4611-bf56-ba8604d8648f/download',
                'url_type': None},
               {'api_access_number': 5,
                'api_access_number_absolute': 5,
                'cache_last_updated': None,
                'cache_url': None,
                'created': '2025-07-23T07:07:04.945912',
                'datastore_active': True,
                'description': '',
                'downloads': 38,
                'downloads_absolute': 39,
                'format': 'CSV',
                'hash': '',
                'hide_url': 'No',
                'id': '657384c4-8d9b-45cb-845d-0649eb88e35a',
                'last_modified': None,
                'map_visualization_res': 'none',
                'mimetype': None,
                'mimetype_inner': None,
                'name': '2021_pad_emi_mdbas.csv',
                'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
                'position': 6,
                'qa': {'archival_timestamp': None,
                       'created': '2025-07-24T02:10:38.595194',
                       'format': 'CSV',
                       'openness_score': 3,
                       'openness_score_reason': 'This file had not been '
                                                'downloaded at the time of '
                                                'scoring it. URL extension '
                                                '"csv" relates to format "CSV" '
                                                'and receives score: 3.',
                       'resource_timestamp': None,
                       'updated': '2026-04-23T02:08:56.715485'},
                'resource_type': None,
                'revision_id': '94e75370-9886-470d-aa39-be8db57eec87',
                'size': '56172',
                'state': 'active',
                'token_provider': '',
                'token_required': 'No',
                'token_type': '',
                'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/3d317361-0be9-4178-8566-4ff0b33d65a3/resource/657384c4-8d9b-45cb-845d-0649eb88e35a/download',
                'url_type': None},
               {'api_access_number': 0,
                'api_access_number_absolute': 0,
                'cache_last_updated': None,
                'cache_url': None,
                'created': '2025-07-23T07:05:47.722924',
                'datastore_active': False,
                'description': '',
                'downloads': 19,
                'downloads_absolute': 19,
                'format': 'JSON',
                'hash': '',
                'hide_url': 'No',
                'id': 'f55e3330-52ad-41fd-b57e-3ec846555e04',
                'last_modified': None,
                'map_visualization_res': 'none',
                'mimetype': None,
                'mimetype_inner': None,
                'name': '2021_pad_emi_mdbas.json',
                'package_id': '3d317361-0be9-4178-8566-4ff0b33d65a3',
                'position': 7,

### 2. Dels resultats obtinguts, selecciona’n un que tingui recursos disponibles en CSV o JSON.

In [27]:
for d in datasets:
    formats = set()  # per evitar duplicats
    
    for r in d["resources"]:
        fmt = r["format"]
        if fmt:  # evitar buits
            formats.add(fmt.upper())
    
    print(f"{d['title']} → {', '.join(formats)}")

Number of real estate property transactions, based on notarial records, by property use → CSV
Area (m²) of real estate properties transmitted by sale transaction, based on notarials records, by property use → CSV
Fees excluding VAT from the public price register for waste collection (excluding large producers) of the Barcelona City Council → CSV
Receipts and quota of the register of the Vados Tax of the Barcelona City Council → CSV
Receipts and charges from the motor vehicle tax roll of the Barcelona City Council → CSV
Immigrants → JSON, CSV
Emigrants → JSON, CSV
Cancellations for undue inscription → JSON, CSV
Registrations by omission → JSON, CSV
Deaths → JSON, CSV

### 3. Amb el resource_id del recurs seleccionat, realitza una consulta mitjançant datastore_search per:

Recuperar almenys 100 registres.

In [28]:
# seleccionar dataset
d = datasets[6]

# agafar primer resource amb datastore
resource_id = next(r["id"] for r in d["resources"] if r.get("datastore_active"))

# consulta
url = "https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search"
params = {"resource_id": resource_id, "limit": 100}

data = requests.get(url, params=params).json()

print(len(data["result"]["records"]))

100

In [29]:
data

{'help': 'https://opendata-ajuntament.barcelona.cat/data/api/3/action/help_show?name=datastore_search',
 'success': True,
 'result': {'resource_id': '41964dc5-927b-4a09-bf5a-59ab8927ee0e',
  'fields': [{'type': 'int4', 'id': '_id'},
   {'type': 'numeric', 'id': 'Any'},
   {'type': 'numeric', 'id': 'Codi_Districte'},
   {'type': 'text', 'id': 'Nom_Districte'},
   {'type': 'numeric', 'id': 'Codi_Barri'},
   {'type': 'text', 'id': 'Nom_Barri'},
   {'type': 'numeric', 'id': 'AEB'},
   {'type': 'numeric', 'id': 'Seccio_Censal'},
   {'type': 'numeric', 'id': 'Valor'}],
  'records': [{'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Raval',
    'AEB': '1',
    'Seccio_Censal': '1001',
    'Valor': '70',
    'Codi_Barri': '1',
    '_id': 1,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Raval',
    'AEB': '1',
    'Seccio_Censal': '1002',
    'Valor': '74',
    'Codi_Barri': '1',
    '_id': 2,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Raval',
    'AEB': '2',
    'Seccio_Censal': '1003',
    'Valor': '218',
    'Codi_Barri': '1',
    '_id': 3,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Raval',
    'AEB': '2',
    'Seccio_Censal': '1004',
    'Valor': '160',
    'Codi_Barri': '1',
    '_id': 4,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Raval',
    'AEB': '3',
    'Seccio_Censal': '1005',
    'Valor': '103',
    'Codi_Barri': '1',
    '_id': 5,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Raval',
    'AEB': '3',
    'Seccio_Censal': '1006',
    'Valor': '67',
    'Codi_Barri': '1',
    '_id': 6,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Raval',
    'AEB': '3',
    'Seccio_Censal': '1007',
    'Valor': '101',
    'Codi_Barri': '1',
    '_id': 7,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Raval',
    'AEB': '4',
    'Seccio_Censal': '1008',
    'Valor': '202',
    'Codi_Barri': '1',
    '_id': 8,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Raval',
    'AEB': '4',
    'Seccio_Censal': '1009',
    'Valor': '124',
    'Codi_Barri': '1',
    '_id': 9,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Raval',
    'AEB': '4',
    'Seccio_Censal': '1010',
    'Valor': '118',
    'Codi_Barri': '1',
    '_id': 10,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Raval',
    'AEB': '5',
    'Seccio_Censal': '1011',
    'Valor': '173',
    'Codi_Barri': '1',
    '_id': 11,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Raval',
    'AEB': '5',
    'Seccio_Censal': '1012',
    'Valor': '93',
    'Codi_Barri': '1',
    '_id': 12,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Raval',
    'AEB': '5',
    'Seccio_Censal': '1013',
    'Valor': '46',
    'Codi_Barri': '1',
    '_id': 13,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Raval',
    'AEB': '6',
    'Seccio_Censal': '1014',
    'Valor': '77',
    'Codi_Barri': '1',
    '_id': 14,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Raval',
    'AEB': '6',
    'Seccio_Censal': '1015',
    'Valor': '80',
    'Codi_Barri': '1',
    '_id': 15,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Raval',
    'AEB': '6',
    'Seccio_Censal': '1016',
    'Valor': '97',
    'Codi_Barri': '1',
    '_id': 16,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Raval',
    'AEB': '6',
    'Seccio_Censal': '1017',
    'Valor': '131',
    'Codi_Barri': '1',
    '_id': 17,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Raval',
    'AEB': '7',
    'Seccio_Censal': '1018',
    'Valor': '66',
    'Codi_Barri': '1',
    '_id': 18,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Raval',
    'AEB': '7',
    'Seccio_Censal': '1019',
    'Valor': '140',
    'Codi_Barri': '1',
    '_id': 19,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Raval',
    'AEB': '7',
    'Seccio_Censal': '1020',
    'Valor': '121',
    'Codi_Barri': '1',
    '_id': 20,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Raval',
    'AEB': '8',
    'Seccio_Censal': '1021',
    'Valor': '130',
    'Codi_Barri': '1',
    '_id': 21,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Barri Gòtic',
    'AEB': '9',
    'Seccio_Censal': '1022',
    'Valor': '113',
    'Codi_Barri': '2',
    '_id': 22,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Barri Gòtic',
    'AEB': '9',
    'Seccio_Censal': '1023',
    'Valor': '95',
    'Codi_Barri': '2',
    '_id': 23,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Barri Gòtic',
    'AEB': '10',
    'Seccio_Censal': '1025',
    'Valor': '74',
    'Codi_Barri': '2',
    '_id': 24,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Barri Gòtic',
    'AEB': '10',
    'Seccio_Censal': '1026',
    'Valor': '890',
    'Codi_Barri': '2',
    '_id': 25,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Barri Gòtic',
    'AEB': '10',
    'Seccio_Censal': '1027',
    'Valor': '126',
    'Codi_Barri': '2',
    '_id': 26,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Barri Gòtic',
    'AEB': '11',
    'Seccio_Censal': '1028',
    'Valor': '123',
    'Codi_Barri': '2',
    '_id': 27,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Barri Gòtic',
    'AEB': '11',
    'Seccio_Censal': '1029',
    'Valor': '97',
    'Codi_Barri': '2',
    '_id': 28,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Barri Gòtic',
    'AEB': '12',
    'Seccio_Censal': '1030',
    'Valor': '147',
    'Codi_Barri': '2',
    '_id': 29,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'el Barri Gòtic',
    'AEB': '12',
    'Seccio_Censal': '1031',
    'Valor': '122',
    'Codi_Barri': '2',
    '_id': 30,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'la Barceloneta',
    'AEB': '13',
    'Seccio_Censal': '1032',
    'Valor': '78',
    'Codi_Barri': '3',
    '_id': 31,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'la Barceloneta',
    'AEB': '13',
    'Seccio_Censal': '1033',
    'Valor': '68',
    'Codi_Barri': '3',
    '_id': 32,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'la Barceloneta',
    'AEB': '13',
    'Seccio_Censal': '1034',
    'Valor': '63',
    'Codi_Barri': '3',
    '_id': 33,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'la Barceloneta',
    'AEB': '14',
    'Seccio_Censal': '1035',
    'Valor': '74',
    'Codi_Barri': '3',
    '_id': 34,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'la Barceloneta',
    'AEB': '14',
    'Seccio_Censal': '1036',
    'Valor': '45',
    'Codi_Barri': '3',
    '_id': 35,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'la Barceloneta',
    'AEB': '15',
    'Seccio_Censal': '1037',
    'Valor': '65',
    'Codi_Barri': '3',
    '_id': 36,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'la Barceloneta',
    'AEB': '15',
    'Seccio_Censal': '1038',
    'Valor': '90',
    'Codi_Barri': '3',
    '_id': 37,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'la Barceloneta',
    'AEB': '15',
    'Seccio_Censal': '1039',
    'Valor': '60',
    'Codi_Barri': '3',
    '_id': 38,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'la Barceloneta',
    'AEB': '15',
    'Seccio_Censal': '1040',
    'Valor': '60',
    'Codi_Barri': '3',
    '_id': 39,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'la Barceloneta',
    'AEB': '15',
    'Seccio_Censal': '1041',
    'Valor': '87',
    'Codi_Barri': '3',
    '_id': 40,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'la Barceloneta',
    'AEB': '15',
    'Seccio_Censal': '1042',
    'Valor': '80',
    'Codi_Barri': '3',
    '_id': 41,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'Sant Pere, Santa Caterina i la Ribera',
    'AEB': '16',
    'Seccio_Censal': '1043',
    'Valor': '72',
    'Codi_Barri': '4',
    '_id': 42,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'Sant Pere, Santa Caterina i la Ribera',
    'AEB': '16',
    'Seccio_Censal': '1044',
    'Valor': '78',
    'Codi_Barri': '4',
    '_id': 43,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'Sant Pere, Santa Caterina i la Ribera',
    'AEB': '16',
    'Seccio_Censal': '1045',
    'Valor': '121',
    'Codi_Barri': '4',
    '_id': 44,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'Sant Pere, Santa Caterina i la Ribera',
    'AEB': '16',
    'Seccio_Censal': '1046',
    'Valor': '74',
    'Codi_Barri': '4',
    '_id': 45,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'Sant Pere, Santa Caterina i la Ribera',
    'AEB': '17',
    'Seccio_Censal': '1047',
    'Valor': '90',
    'Codi_Barri': '4',
    '_id': 46,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'Sant Pere, Santa Caterina i la Ribera',
    'AEB': '17',
    'Seccio_Censal': '1048',
    'Valor': '108',
    'Codi_Barri': '4',
    '_id': 47,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'Sant Pere, Santa Caterina i la Ribera',
    'AEB': '17',
    'Seccio_Censal': '1049',
    'Valor': '64',
    'Codi_Barri': '4',
    '_id': 48,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'Sant Pere, Santa Caterina i la Ribera',
    'AEB': '18',
    'Seccio_Censal': '1050',
    'Valor': '89',
    'Codi_Barri': '4',
    '_id': 49,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'Sant Pere, Santa Caterina i la Ribera',
    'AEB': '18',
    'Seccio_Censal': '1051',
    'Valor': '97',
    'Codi_Barri': '4',
    '_id': 50,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'Sant Pere, Santa Caterina i la Ribera',
    'AEB': '18',
    'Seccio_Censal': '1052',
    'Valor': '83',
    'Codi_Barri': '4',
    '_id': 51,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'Sant Pere, Santa Caterina i la Ribera',
    'AEB': '19',
    'Seccio_Censal': '1053',
    'Valor': '76',
    'Codi_Barri': '4',
    '_id': 52,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'Sant Pere, Santa Caterina i la Ribera',
    'AEB': '19',
    'Seccio_Censal': '1054',
    'Valor': '48',
    'Codi_Barri': '4',
    '_id': 53,
    'Any': '2024'},
   {'Codi_Districte': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Nom_Barri': 'Sant Pere, Santa Caterina i la Ribera',
    'AEB': '19',
    'Seccio_Censal': '1055',
    'Valor': '48',
    'Codi_Barri': '4',
    '_id': 54,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'el Fort Pienc',
    'AEB': '20',
    'Seccio_Censal': '2001',
    'Valor': '48',
    'Codi_Barri': '5',
    '_id': 55,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'el Fort Pienc',
    'AEB': '20',
    'Seccio_Censal': '2002',
    'Valor': '508',
    'Codi_Barri': '5',
    '_id': 56,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'el Fort Pienc',
    'AEB': '20',
    'Seccio_Censal': '2003',
    'Valor': '34',
    'Codi_Barri': '5',
    '_id': 57,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'el Fort Pienc',
    'AEB': '20',
    'Seccio_Censal': '2004',
    'Valor': '62',
    'Codi_Barri': '5',
    '_id': 58,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'el Fort Pienc',
    'AEB': '20',
    'Seccio_Censal': '2005',
    'Valor': '96',
    'Codi_Barri': '5',
    '_id': 59,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'el Fort Pienc',
    'AEB': '20',
    'Seccio_Censal': '2006',
    'Valor': '60',
    'Codi_Barri': '5',
    '_id': 60,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'el Fort Pienc',
    'AEB': '20',
    'Seccio_Censal': '2007',
    'Valor': '43',
    'Codi_Barri': '5',
    '_id': 61,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'el Fort Pienc',
    'AEB': '20',
    'Seccio_Censal': '2008',
    'Valor': '66',
    'Codi_Barri': '5',
    '_id': 62,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'el Fort Pienc',
    'AEB': '20',
    'Seccio_Censal': '2009',
    'Valor': '72',
    'Codi_Barri': '5',
    '_id': 63,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'el Fort Pienc',
    'AEB': '21',
    'Seccio_Censal': '2010',
    'Valor': '58',
    'Codi_Barri': '5',
    '_id': 64,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'el Fort Pienc',
    'AEB': '21',
    'Seccio_Censal': '2011',
    'Valor': '50',
    'Codi_Barri': '5',
    '_id': 65,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'el Fort Pienc',
    'AEB': '21',
    'Seccio_Censal': '2012',
    'Valor': '86',
    'Codi_Barri': '5',
    '_id': 66,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'el Fort Pienc',
    'AEB': '21',
    'Seccio_Censal': '2013',
    'Valor': '51',
    'Codi_Barri': '5',
    '_id': 67,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'el Fort Pienc',
    'AEB': '22',
    'Seccio_Censal': '2014',
    'Valor': '71',
    'Codi_Barri': '5',
    '_id': 68,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'el Fort Pienc',
    'AEB': '22',
    'Seccio_Censal': '2015',
    'Valor': '65',
    'Codi_Barri': '5',
    '_id': 69,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'el Fort Pienc',
    'AEB': '22',
    'Seccio_Censal': '2016',
    'Valor': '76',
    'Codi_Barri': '5',
    '_id': 70,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'el Fort Pienc',
    'AEB': '22',
    'Seccio_Censal': '2017',
    'Valor': '83',
    'Codi_Barri': '5',
    '_id': 71,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'el Fort Pienc',
    'AEB': '22',
    'Seccio_Censal': '2018',
    'Valor': '66',
    'Codi_Barri': '5',
    '_id': 72,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'el Fort Pienc',
    'AEB': '22',
    'Seccio_Censal': '2019',
    'Valor': '86',
    'Codi_Barri': '5',
    '_id': 73,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'el Fort Pienc',
    'AEB': '22',
    'Seccio_Censal': '2020',
    'Valor': '76',
    'Codi_Barri': '5',
    '_id': 74,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'la Sagrada Família',
    'AEB': '23',
    'Seccio_Censal': '2021',
    'Valor': '65',
    'Codi_Barri': '6',
    '_id': 75,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'la Sagrada Família',
    'AEB': '23',
    'Seccio_Censal': '2022',
    'Valor': '49',
    'Codi_Barri': '6',
    '_id': 76,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'la Sagrada Família',
    'AEB': '23',
    'Seccio_Censal': '2023',
    'Valor': '32',
    'Codi_Barri': '6',
    '_id': 77,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'la Sagrada Família',
    'AEB': '23',
    'Seccio_Censal': '2024',
    'Valor': '63',
    'Codi_Barri': '6',
    '_id': 78,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'la Sagrada Família',
    'AEB': '24',
    'Seccio_Censal': '2025',
    'Valor': '47',
    'Codi_Barri': '6',
    '_id': 79,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'la Sagrada Família',
    'AEB': '24',
    'Seccio_Censal': '2026',
    'Valor': '98',
    'Codi_Barri': '6',
    '_id': 80,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'la Sagrada Família',
    'AEB': '24',
    'Seccio_Censal': '2027',
    'Valor': '82',
    'Codi_Barri': '6',
    '_id': 81,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'la Sagrada Família',
    'AEB': '24',
    'Seccio_Censal': '2028',
    'Valor': '92',
    'Codi_Barri': '6',
    '_id': 82,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'la Sagrada Família',
    'AEB': '24',
    'Seccio_Censal': '2029',
    'Valor': '51',
    'Codi_Barri': '6',
    '_id': 83,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'la Sagrada Família',
    'AEB': '24',
    'Seccio_Censal': '2030',
    'Valor': '61',
    'Codi_Barri': '6',
    '_id': 84,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'la Sagrada Família',
    'AEB': '24',
    'Seccio_Censal': '2031',
    'Valor': '26',
    'Codi_Barri': '6',
    '_id': 85,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'la Sagrada Família',
    'AEB': '24',
    'Seccio_Censal': '2032',
    'Valor': '48',
    'Codi_Barri': '6',
    '_id': 86,
    'Any': '2024'},
   {'Codi_Districte': '2',
    'Nom_Districte': 'Eixample',
    'Nom_Barri': 'la Sagrada Família',
    'AEB': '25',
    'Seccio_Censal': '2033',
    'Valor': '54',
    'Codi_Barri': '6',
    '_id': 87,
    'Any': '2024'},
   {'Codi_Districte': '2',

### 4. Converteix els resultats a un DataFrame.

In [30]:
records = data["result"]["records"]

df = pd.DataFrame(records)

display(df.head())

,Codi_Districte,Nom_Districte,Nom_Barri,AEB,Seccio_Censal,Valor,Codi_Barri,_id,Any
0,1,Ciutat Vella,el Raval,1,1001,70,1,1,2024
1,1,Ciutat Vella,el Raval,1,1002,74,1,2,2024
2,1,Ciutat Vella,el Raval,2,1003,218,1,3,2024
3,1,Ciutat Vella,el Raval,2,1004,160,1,4,2024
4,1,Ciutat Vella,el Raval,3,1005,103,1,5,2024

### 5. Desa el DataFrame en un fitxer .csv.

In [31]:
df.to_csv('./data/emigrants.csv')

# Pàgines Web

- [PATCH method - Python requests](https://www.geeksforgeeks.org/python/patch-method-python-requests/)