# Tasca S11.01. Visualització de Dades amb Python i Power BI

**Descripció**  
Aquesta pràctica integra l'ús de Python amb les llibreries Pandas, Matplotlib, Seaborn o Plotly, així com la seva integració amb Power BI. Treballaràs tot el procés des de la connexió a MySQL, la creació de visualitzacions avançades en Python i finalment la incorporació d'aquestes visualitzacions a un informe dinàmic a Power BI.

## Llibreries

In [1]:
import mysql.connector
from mysql.connector import Error

from dotenv import load_dotenv  
import os

load_dotenv()

import pandas as pd
import matplotlib as plt

## **Nivell 1**

### **1. Connecta Python amb MySQL Workbench i carrega les dades de la teva base de dades del Sprint 4 per utilitzar-les en tots els exercicis.**

#### Connexió amb la base de dades s4_transactions

In [2]:
try:
    connection = mysql.connector.connect(host=os.getenv("DB_HOST"),
                                         database='s4_transactions',
                                         user=os.getenv('DB_USER'),
                                         password=os.getenv('DB_PASSWORD'))
    if connection.is_connected():
        cursor = connection.cursor(buffered=True)
        cursor.execute("select database();")
        record = cursor.fetchone()
        print("You're connected to database: ", record)

except Error as e:
    print("Error while connecting to MySQL", e)

You're connected to database:  ('s4_transactions',)

#### Càrrega de la base de dades s4_transactions

In [3]:
cursor.execute("Show tables;")

tables = cursor.fetchall()

for x in tables:
    print(x)
    print(type(x))

('active_credit_cards',)
<class 'tuple'>
('all_users',)
<class 'tuple'>
('companies',)
<class 'tuple'>
('credit_cards',)
<class 'tuple'>
('products',)
<class 'tuple'>
('transaction_product',)
<class 'tuple'>
('transactions',)
<class 'tuple'>

###### Create a dictionary of tuples

In [4]:
def select_table(table_name: str):
    query = f"SELECT * FROM {table_name}"
    cursor.execute(query)
    
    data = cursor.fetchall()
    columns = [col[0] for col in cursor.description]
    
    return {
        "columns": columns,
        "data": data
    }

In [5]:
tables_data = {}

for x in tables:
    table_name = x[0]
    tables_data[table_name] = select_table(table_name)

In [6]:
tables_data['companies']

{'columns': ['company_id',
  'company_name',
  'phone',
  'email',
  'country',
  'website'],
 'data': [('b-2222',
   'Ac Fermentum Incorporated',
   '06 85 56 52 33',
   'donec.porttitor.tellus@yahoo.net',
   'Germany',
   'https://instagram.com/site\r'),
  ('b-2226',
   'Magna A Neque Industries',
   '04 14 44 64 62',
   'risus.donec.nibh@icloud.org',
   'Australia',
   'https://whatsapp.com/group/9\r'),
  ('b-2230',
   'Fusce Corp.',
   '08 14 97 58 85',
   'risus@protonmail.edu',
   'United States',
   'https://pinterest.com/sub/cars\r'),
  ('b-2234',
   'Convallis In Incorporated',
   '06 66 57 29 50',
   'mauris.ut@aol.couk',
   'Germany',
   'https://cnn.com/user/110\r'),
  ('b-2238',
   'Ante Iaculis Nec Foundation',
   '08 23 04 99 53',
   'sed.dictum.proin@outlook.ca',
   'New Zealand',
   'https://netflix.com/settings\r'),
  ('b-2242',
   'Donec Ltd',
   '01 25 51 37 37',
   'at.iaculis@hotmail.couk',
   'Norway',
   'https://nytimes.com/user/110\r'),
  ('b-2246',
   'Sed Nunc Ltd',
   '02 62 64 73 48',
   'nibh@yahoo.org',
   'United Kingdom',
   'https://cnn.com/one\r'),
  ('b-2250',
   'Amet Nulla Donec Corporation',
   '07 15 25 14 74',
   'mattis.integer.eu@protonmail.net',
   'Italy',
   'https://netflix.com/sub/cars\r'),
  ('b-2254',
   'Nascetur Ridiculus Mus Inc.',
   '06 26 87 61 84',
   'suspendisse.dui@icloud.net',
   'United States',
   'https://ebay.com/sub\r'),
  ('b-2258',
   'Vestibulum Lorem PC',
   '02 02 87 33 40',
   'aenean.massa.integer@aol.net',
   'Belgium',
   'https://pinterest.com/sub/cars\r'),
  ('b-2262',
   'Gravida Sagittis LLP',
   '03 81 28 33 97',
   'turpis.vitae@google.ca',
   'Sweden',
   'https://naver.com/site\r'),
  ('b-2266',
   'Mus Aenean Eget Foundation',
   '06 25 15 52 43',
   'mi.duis@hotmail.net',
   'Sweden',
   'https://instagram.com/group/9\r'),
  ('b-2270',
   'Dis Parturient Institute',
   '05 36 29 78 74',
   'purus@protonmail.org',
   'Ireland',
   'https://google.com/one\r'),
  ('b-2274',
   'Sed LLC',
   '01 63 16 26 52',
   'at@outlook.com',
   'Belgium',
   'https://reddit.com/fr\r'),
  ('b-2278',
   'Arcu LLP',
   '06 46 04 41 45',
   'dui@aol.ca',
   'Norway',
   'https://yahoo.com/sub\r'),
  ('b-2282',
   'Pretium Neque Corp.',
   '07 77 48 55 28',
   'eleifend.nec.malesuada@protonmail.couk',
   'Australia',
   'https://netflix.com/sub\r'),
  ('b-2286',
   'Fringilla LLC',
   '08 29 15 93 57',
   'gravida@protonmail.couk',
   'New Zealand',
   'https://reddit.com/user/110\r'),
  ('b-2290',
   'Quisque Libero LLC',
   '01 45 48 71 11',
   'sapien.molestie.orci@hotmail.couk',
   'China',
   'https://baidu.com/group/9\r'),
  ('b-2294',
   'Auctor Mauris Vel LLP',
   '08 09 28 74 14',
   'nec.tempus@icloud.couk',
   'United States',
   'https://instagram.com/fr\r'),
  ('b-2298',
   'Elit Etiam Laoreet Associates',
   '07 69 74 17 45',
   'ultrices@google.couk',
   'Canada',
   'https://yahoo.com/fr\r'),
  ('b-2302',
   'Nunc Interdum Incorporated',
   '05 18 15 48 13',
   'non@outlook.com',
   'Germany',
   'https://wikipedia.org/en-us\r'),
  ('b-2306',
   'Augue Foundation',
   '06 88 43 15 63',
   'mauris@yahoo.com',
   'Germany',
   'https://baidu.com/sub/cars\r'),
  ('b-2310',
   'Non Magna LLC',
   '06 71 73 13 17',
   'nisl.quisque.fringilla@hotmail.ca',
   'United Kingdom',
   'https://whatsapp.com/site\r'),
  ('b-2314',
   'A Institute',
   '03 34 91 68 65',
   'metus.aliquam@google.edu',
   'Belgium',
   'https://reddit.com/fr\r'),
  ('b-2318',
   'Quam A Felis Industries',
   '04 87 10 27 16',
   'proin.velit@icloud.edu',
   'Italy',
   'https://ebay.com/settings\r'),
  ('b-2322',
   'Integer Mollis Corp.',
   '03 12 20 45 24',
   'eu.eros@protonmail.ca',
   'Italy',
   'https://netflix.com/group/9\r'),
  ('b-2326',
   'Enim Condimentum Ltd',
   '09 55 51 66 25',
   'imperdiet.non.vestibulum@yahoo.net',
   'United Kingdom',
   'https://cnn.com/group/9\r'),
  ('b-2330',
   'Donec Fringilla PC',
   '01 51 58 14 44',
   'ut.tincidunt@hotmail.ca',
   'France',
   'https://google.com/fr\r'),
  ('b-2334',
   'Amet Institute',
   '06 33 40 21 33',
   'nullam.lobortis.quam@outlook.net',
   'Australia',
   'https://nytimes.com/one\r'),
  ('b-2338',
   'Magna Incorporated',
   '07 73 69 44 18',
   'non@google.net',
   'New Zealand',
   'https://twitter.com/en-us\r'),
  ('b-2342',
   'Fringilla Porttitor Incorporated',
   '06 30 30 97 81',
   'ultrices.a.auctor@protonmail.couk',
   'Sweden',
   'https://wikipedia.org/settings\r'),
  ('b-2346',
   'Ut Semper Foundation',
   '01 60 36 33 06',
   'consectetuer@google.ca',
   'Sweden',
   'https://ebay.com/settings\r'),
  ('b-2350',
   'Aliquet Vel Vulputate Incorporated',
   '04 40 43 84 18',
   'suspendisse.commodo@outlook.couk',
   'Netherlands',
   'https://facebook.com/one\r'),
  ('b-2354',
   'Ac Libero Inc.',
   '04 36 20 64 29',
   'mollis.lectus@protonmail.ca',
   'United Kingdom',
   'https://reddit.com/one\r'),
  ('b-2358',
   'Ac Industries',
   '09 34 65 40 60',
   'ipsum@yahoo.com',
   'Germany',
   'https://bbc.co.uk/group/9\r'),
  ('b-2362',
   'Lorem Eu Incorporated',
   '01 83 66 62 07',
   'enim.gravida.sit@hotmail.net',
   'Canada',
   'https://baidu.com/en-ca\r'),
  ('b-2366',
   'Mauris Institute',
   '05 29 60 36 87',
   'morbi.vehicula@outlook.couk',
   'Sweden',
   'https://ebay.com/sub/cars\r'),
  ('b-2370',
   'Non Justo Corp.',
   '09 30 54 14 44',
   'urna.ut.tincidunt@yahoo.edu',
   'Sweden',
   'https://baidu.com/en-us\r'),
  ('b-2374',
   'Amet Faucibus Ut Foundation',
   '03 21 62 47 12',
   'malesuada@icloud.net',
   'United Kingdom',
   'https://zoom.us/fr\r'),
  ('b-2378',
   'Erat LLP',
   '03 18 88 77 79',
   'non.vestibulum@protonmail.net',
   'Netherlands',
   'https://ebay.com/fr\r'),
  ('b-2382',
   'Neque Tellus Incorporated',
   '04 43 18 34 19',
   'ultrices.iaculis.odio@aol.ca',
   'Ireland',
   'https://google.com/site\r'),
  ('b-2386',
   'Lacus Quisque Associates',
   '06 26 86 55 77',
   'convallis@yahoo.couk',
   'United States',
   'https://baidu.com/group/9\r'),
  ('b-2390',
   'Neque Tellus Imperdiet Corp.',
   '09 15 42 22 11',
   'vestibulum.ante.ipsum@aol.edu',
   'Ireland',
   'https://whatsapp.com/sub/cars\r'),
  ('b-2394',
   'Tortor Nunc Commodo Company',
   '05 35 92 77 16',
   'placerat.cras@hotmail.net',
   'United States',
   'https://zoom.us/settings\r'),
  ('b-2398',
   'Eget Ipsum Ltd',
   '03 67 44 56 72',
   'lacinia.at.iaculis@hotmail.net',
   'United States',
   'https://whatsapp.com/settings\r'),
  ('b-2402',
   'At Pede Corp.',
   '06 14 48 33 15',
   'ac.mi.eleifend@hotmail.edu',
   'Italy',
   'https://netflix.com/site\r'),
  ('b-2406',
   'Non Ante LLP',
   '08 89 47 65 08',
   'at.augue.id@aol.net',
   'Sweden',
   'https://nytimes.com/group/9\r'),
  ('b-2410',
   'Sed Id Limited',
   '07 28 18 18 13',
   'iaculis.enim@outlook.net',
   'United States',
   'https://netflix.com/sub/cars\r'),
  ('b-2414',
   'Netus Et Malesuada Ltd',
   '02 55 43 68 46',
   'et.ipsum.cursus@aol.edu',
   'Netherlands',
   'https://baidu.com/sub/cars\r'),
  ('b-2418',
   'Mauris Id Inc.',
   '04 83 24 50 85',
   'bibendum.sed.est@yahoo.net',
   'Ireland',
   'https://google.com/one\r'),
  ('b-2422',
   'Urna Convallis Associates',
   '06 01 24 77 04',
   'aliquam@yahoo.org',
   'United States',
   'https://cnn.com/sub/cars\r'),
  ('b-2426',
   'Pede Cum Ltd',
   '07 62 26 48 38',
   'lorem.ipsum.sodales@yahoo.ca',
   'Norway',
   'https://cnn.com/one\r'),
  ('b-2430',
   'Interdum Feugiat Sed Associates',
   '04 88 40 32 52',
   'consectetuer.mauris@yahoo.couk',
   'United Kingdom',
   'https://nytimes.com/sub\r'),
  ('b-2434',
   'Tristique Neque Venenatis Institute',
   '04 34 85 12 85',
   'ullamcorper.magna@hotmail.ca',
   'Sweden',
   'https://ebay.com/sub\r'),
  ('b-2438',
   'Nunc Ac PC',
   '03 53 62 76 95',
   'non.ante@google.com',
   'Sweden',
   'https://nytimes.com/fr\r'),
  ('b-2442',
   'Aliquam Erat Volutpat LLP',
   '06 01 63 57 66',
   'pede.nunc@icloud.net',
   'Italy',
   'https://instagram.com/fr\r'),
  ('b-2446',
   'Risus Associates',
   '04 25 82 54 31',
   'egestas.ligula.nullam@google.edu',
   'Australia',
   'https://whatsapp.com/group/9\r'),
  ('b-2450',
   'Turpis Company',
   '09 69 48 65 52',
   'cursus.integer@outlook.ca',
   'Netherlands',
   'https://instagram.com/sub\r'),
  ('b-2454',
   'Justo Eu Arcu Ltd',
   '08 42 56 71 52',
   'ac.facilisis@icloud.couk',
   'Italy',
   'https://nytimes.com/group/9\r'),
  ('b-2458',
   'Eget Tincidunt Dui Institute',
   '05 35 93 32 44',
   'eget.laoreet@hotmail.org',
   'Netherlands',
   'https://wikipedia.org/user/110\r'),
  ('b-2462',
   'Pede Ultrices Ltd',
   '04 52 40 26 17',
   'justo.proin@yahoo.com',
   'Belgium',
   'https://instagram.com/group/9\r'),
  ('b-2466',
   'Amet Lorem LLP',
   '05 47 44 68 02',
   'ultricies.adipiscing@icloud.edu',
   'Spain',
   'https://wikipedia.org/one\r'),
  ('b-2470',
   'Nec Luctus LLC',
   '02 14 71 75 73',
   'consectetuer.cursus@protonmail.couk',
   'Norway',
   'https://instagram.com/user/110\r'),
  ('b-2474',
   'Mauris Incorporated',
   '06 84 33 15 97',
   'nisi.mauris.nulla@hotmail.net',
   'Norway',
   'https://cnn.com/site\r'),
  ('b-2478',
   'Etiam Bibendum Fermentum Industries',
   '07 46 69 45 02',
   'sem.magna@icloud.ca',
   'France',
   'https://youtube.com/one\r'),
  ('b-2482',
   'Dui Cras Associates',
   '08 12 73 87 84',
   'tristique@yahoo.com',
   'Italy',
   'https://reddit.com/fr\r'),
  ('b-2486',
   'Tincidunt Orci Limited',
   '01 78 18 81 44',
   'velit.pellentesque@outlook.edu',
   'Norway',
   'https://nytimes.com/settings\r'),
  ('b-2490',
   'Nunc Sit Incorporated',
   '07 28 42 63 63',
   'pede.ultrices@icloud.net',
   'Norway',
   'https://naver.com/en-ca\r'),
  ('b-2494',
   'Malesuada PC',
   '01 74 85 68 70',
   'cras.lorem.lorem@outlook.com',
   'Ireland',
   'https://yahoo.com/fr\r'),
  ('b-2498',
   'Metus Vitae Associates',
   '08 25 44 40 66',
   'ad@protonmail.com',
   'Australia',
   'https://google.com/site\r'),
  ('b-2502',
   'Dolor Vitae Limited',
   '06 53 60 43 60',
   'purus.maecenas@yahoo.edu',
   'France',
   'https://whatsapp.com/user/110\r'),
  ('b-2506',
   'Sapien Nunc Pulvinar LLP',
   '08 37 12 58 11',
   'sit.amet@yahoo.net',
   'New Zealand',
   'https://netflix.com/settings\r'),
  ('b-2510',
   'Maecenas Malesuada Fringilla Inc.',
   '09 38 53 76 61',
   'id.ante@yahoo.ca',
   'Netherlands',
   'https://zoom.us/en-us\r'),
  ('b-2514',
   'Cras Consulting',
   '07 50 10 85 63',
   'sed.consequat@google.ca',
   'Belgium',
   'https://baidu.com/en-us\r'),
  ('b-2518',
   'Aliquet Sem Limited',
   '03 75 57 02 01',
   'sem.magna@yahoo.edu',
   'Netherlands',
   'https://cnn.com/group/9\r'),
  ('b-2522',
   'Viverra Donec Foundation',
   '03 33 12 32 73',
   'dictum.eu@outlook.net',
   'United Kingdom',
   'https://nytimes.com/site\r'),
  ('b-2526',
   'Amet Luctus Vulputate Foundation',
   '03 18 54 24 19',
   'nulla@outlook.com',
   'Canada',
   'https://netflix.com/en-ca\r'),
  ('b-2530',
   'Tincidunt Associates',
   '09 82 63 76 61',
   'neque.sed@hotmail.com',
   'Ireland',
   'https://netflix.com/site\r'),
  ('b-2534',
   'Mattis Foundation',
   '06 74 03 95 74',
   'sed@google.couk',
   'Australia',
   'https://netflix.com/site\r'),
  ('b-2538',
   'At Associates',
   '09 56 61 10 65',
   'tristique.neque@yahoo.couk',
   'New Zealand',
   'https://walmart.com/one\r'),
  ('b-2542',
   'Nunc In Foundation',
   '03 79 81 18 92',
   'ac.fermentum@protonmail.com',
   'Italy',
   'https://netflix.com/sub\r'),
  ('b-2546',
   'Lorem Ipsum Dolor Corp.',
   '09 03 14 76 02',
   'augue.id@icloud.net',
   'Sweden',
   'https://baidu.com/site\r'),
  ('b-2550',
   'Auctor Mauris Corp.',
   '05 62 87 14 41',
   'eget.metus@protonmail.ca',
   'Germany',
   'https://walmart.com/sub\r'),
  ('b-2554',
   'Cras Vehicula Aliquet Industries',
   '03 37 86 87 75',
   'arcu@hotmail.org',
   'Netherlands',
   'https://google.com/sub\r'),
  ('b-2558',
   'Nulla Integer Vulputate Corp.',
   '04 57 50 84 48',
   'interdum@protonmail.org',
   'Sweden',
   'https://yahoo.com/one\r'),
  ('b-2562',
   'Dictum Eu Corp.',
   '03 04 73 67 31',
   'donec.vitae@icloud.ca',
   'Canada',
   'https://netflix.com/en-ca\r'),
  ('b-2566',
   'Aliquam PC',
   '01 45 73 52 16',
   'scelerisque.mollis@icloud.org',
   'Germany',
   'https://yahoo.com/en-ca\r'),
  ('b-2570',
   'Aliquet Diam Limited',
   '02 76 61 47 46',
   'eu.eros.nam@icloud.org',
   'United States',
   'https://facebook.com/en-us\r'),
  ('b-2574',
   'Orci Adipiscing Limited',
   '03 18 00 77 81',
   'dolor.fusce@protonmail.ca',
   'United Kingdom',
   'https://reddit.com/user/110\r'),
  ('b-2578',
   'Dui Quis Institute',
   '06 93 28 72 81',
   'luctus.sit.amet@yahoo.couk',
   'New Zealand',
   'https://yahoo.com/en-us\r'),
  ('b-2582',
   'Nibh Phasellus Corporation',
   '08 48 67 57 48',
   'nisi@google.edu',
   'China',
   'https://netflix.com/sub/cars\r'),
  ('b-2586',
   'Tempor Diam Institute',
   '05 01 94 80 87',
   'cursus.in@yahoo.com',
   'Netherlands',
   'https://naver.com/settings\r'),
  ('b-2590',
   'Euismod Mauris Institute',
   '02 13 69 54 85',
   'vivamus.molestie@icloud.ca',
   'Belgium',
   'https://ebay.com/en-ca\r'),
  ('b-2594',
   'Et Magnis Ltd',
   '03 53 76 11 76',
   'dapibus.ligula@protonmail.net',
   'Belgium',
   'https://instagram.com/sub\r'),
  ('b-2598',
   'Aliquam Iaculis Lacus Corp.',
   '04 43 07 91 26',
   'dictum@aol.org',
   'Belgium',
   'https://pinterest.com/one\r'),
  ('b-2602',
   'Placerat LLP',
   '05 43 67 24 41',
   'tellus.suspendisse@hotmail.org',
   'Netherlands',
   'https://zoom.us/sub\r'),
  ('b-2606',
   'Sed Est Corp.',
   '04 58 02 37 91',
   'tempor.bibendum@google.couk',
   'Canada',
   'https://instagram.com/sub/cars\r'),
  ('b-2610',
   'Egestas Nunc Sed Limited',
   '06 01 02 70 47',
   'vitae@hotmail.edu',
   'Italy',
   'https://walmart.com/one\r'),
  ('b-2614',
   'Rutrum Non Inc.',
   '02 66 31 61 09',
   'neque@protonmail.net',
   'Germany',
   'https://netflix.com/site\r'),
  ('b-2618',
   'Non Institute',
   '06 77 15 31 14',
   'amet.metus@protonmail.couk',
   'United Kingdom',
   'https://guardian.co.uk/settings\r')]}

###### Create a dictionary of dataframes

In [7]:
def select_table(table_name: str):
    query = f"SELECT * FROM {table_name}"
    cursor.execute(query)
    
    data = cursor.fetchall()
    columns = [col[0] for col in cursor.description]
    index_col = columns[0]

    df = pd.DataFrame(data, columns=columns)
    df.set_index(index_col, inplace=True)
    return df

In [8]:
tables_df = {}

for x in tables:
    table_name = x[0]
    tables_df[table_name] = select_table(table_name)

# tables_df = {table_name: select_table(table_name) for (table_name,) in tables}

In [9]:
tables_df['companies'].head(5)

,company_name,phone,email,country,website
company_id,,,,,
b-2222,Ac Fermentum Incorporated,06 85 56 52 33,donec.porttitor.tellus@yahoo.net,Germany,https://instagram.com/site\r
b-2226,Magna A Neque Industries,04 14 44 64 62,risus.donec.nibh@icloud.org,Australia,https://whatsapp.com/group/9\r
b-2230,Fusce Corp.,08 14 97 58 85,risus@protonmail.edu,United States,https://pinterest.com/sub/cars\r
b-2234,Convallis In Incorporated,06 66 57 29 50,mauris.ut@aol.couk,Germany,https://cnn.com/user/110\r
b-2238,Ante Iaculis Nec Foundation,08 23 04 99 53,sed.dictum.proin@outlook.ca,New Zealand,https://netflix.com/settings\r

#### Tancar cursor i connexió amb MySQL

In [10]:
cursor.close()
connection.close()

if not connection.is_connected():
    print("Connexió tancada correctament ✅")

Connexió tancada correctament ✅

In [11]:
try:
    cursor.execute("SELECT 1")
except:
    print("Cursor tancat o connexió no disponible ✅")

Cursor tancat o connexió no disponible ✅

### **2. Per a cada ítem, crea una visualització adequada segons les variables especificades. Interpreta els resultats segons les teves dades.**

Recorda: quan seleccionis les columnes, pensa sempre en el mètode que faràs servir i inclou les que calguin per a la funció de visualització que vulguis utilitzar.

- Una variable numèrica.
- Dues variables numèriques.
- Una variable categòrica.
- Una variable categòrica i una numèrica.
- Dues variables categòriques.
- Tres variables combinades.
- Crea un Pairplot.

#### Taules disponibles

In [12]:
type(tables_df)

dict

In [13]:
for x, y in tables_df.items():
    print(x)
    display(y.head(5))
    print("-----")

active_credit_cards

           state
card_id
CcS-4857  active
CcS-4858  active
CcS-4859  active
CcS-4860  active
CcS-4861  active

-----
all_users

,name,surname,phone,email,birth_date,country,city,postal_code,address,region
id,,,,,,,,,,
1,Zeus,Gamble,1-282-581-0551,interdum.enim@protonmail.edu,"Nov 17, 1985",United States,New York,10001,348-7818 Sagittis St.,america
10,Robert,Mccarthy,(324) 746-6771,fermentum@protonmail.com,"Apr 30, 1984",United States,San Jose,95101,P.O. Box 773,america
100,Melodie,Mclean,1-677-221-7152,risus.varius@google.ca,"Sep 15, 1989",United States,San Jose,95101,Ap #644-8492 Sagittis St.,america
1000,Amkjrv,Qbulrxbp,+48-258-9936,amkjrv.qbulrxbp@example.com,"May 17, 1970",Germany,Stuttgart,70173,215 Qbulrxbp St,europe
1001,Nfvrlb,Oydaiwbg,+94-121-2522,nfvrlb.oydaiwbg@example.com,"Mar 4, 1994",Germany,Cologne,50667,121 Oydaiwbg St,europe

-----
companies

,company_name,phone,email,country,website
company_id,,,,,
b-2222,Ac Fermentum Incorporated,06 85 56 52 33,donec.porttitor.tellus@yahoo.net,Germany,https://instagram.com/site\r
b-2226,Magna A Neque Industries,04 14 44 64 62,risus.donec.nibh@icloud.org,Australia,https://whatsapp.com/group/9\r
b-2230,Fusce Corp.,08 14 97 58 85,risus@protonmail.edu,United States,https://pinterest.com/sub/cars\r
b-2234,Convallis In Incorporated,06 66 57 29 50,mauris.ut@aol.couk,Germany,https://cnn.com/user/110\r
b-2238,Ante Iaculis Nec Foundation,08 23 04 99 53,sed.dictum.proin@outlook.ca,New Zealand,https://netflix.com/settings\r

-----
credit_cards

,user_id,iban,pan,pin,cvv,track1,track2,expiring_date
id,,,,,,,,
CcS-4857,276,XX4857591835292505850771,2314242385113924,1819,467,%B2314242385113924^LWCBUDLWCBUD^22060000000000...,%B2314242385113924=2410101518363164?,09/27/25
CcS-4858,277,XX8581768137002436094025,6582720299715533,3964,817,%B6582720299715533^TIQMVITIQMVI^24040000000000...,%B6582720299715533=2411101104546272?,12/28/28
CcS-4859,278,XX7826930491423553609370,8861684536289642,4983,277,%B8861684536289642^COFBGDCOFBGD^28020000000000...,%B8861684536289642=2502101761665371?,11/26/26
CcS-4860,279,XX5559590368835304645299,2481155515498459,6876,661,%B2481155515498459^TIUJTUTIUJTU^31040000000000...,%B2481155515498459=2602101514414395?,07/27/27
CcS-4861,280,XX2035182877195191627307,1308930301149557,5710,398,%B1308930301149557^HPOBNZHPOBNZ^33010000000000...,%B1308930301149557=2805101751305028?,04/25/26

-----
products

              product_name    price   colour weight warehouse_id
id
1         Direwolf Stannis  $161.11  #7c7c7c      1         WH-4
2              Tarly Stark    $9.24  #919191      2         WH-3
3   duel tourney Lannister  $171.13  #d8d8d8    1.5         WH-2
4        warden south duel   $71.89  #111111      3         WH-1
5           skywalker ewok  $171.22  #dbdbdb    3.2         WH-0

-----
transaction_product

                                      product_id
transaction_id
00043A49-2949-494B-A5DD-A5BAE3BB19DD          16
00043A49-2949-494B-A5DD-A5BAE3BB19DD          26
00043A49-2949-494B-A5DD-A5BAE3BB19DD          97
00043A49-2949-494B-A5DD-A5BAE3BB19DD          87
000447FE-B650-4DCF-85DE-C7ED0EE1CAAD          66

-----
transactions

,card_id,business_id,transaction_date,amount,declined,product_ids,user_id,lat,longitude
id,,,,,,,,,
00043A49-2949-494B-A5DD-A5BAE3BB19DD,CcS-9294,b-2458,2024-08-28 07:16:46,395.43,0,"16, 26, 97, 87",4713,46.19992926158272,1.4355402821327607
000447FE-B650-4DCF-85DE-C7ED0EE1CAAD,CcS-5019,b-2370,2016-12-21 20:07:18,155.63,0,"66, 69, 87",438,41.59720554463741,12.22175994259365
00045D6B-ED2E-4F2F-8186-CEE074D875D0,CcS-6699,b-2390,2020-07-14 15:37:45,326.01,0,"30, 11, 16, 81",2118,29.757295899964348,-95.37963676492454
000481C3-1C26-4FEF-83A0-4CD0EB004BBD,CcS-6696,b-2230,2017-09-04 19:44:53,161.6,0,72,2115,53.54888376797025,-113.50305274646564
00051AA4-9CBE-4268-B070-C38062A1B3E2,CcS-7606,b-2266,2017-01-05 18:19:25,148.91,0,18,3025,52.20836951654172,5.690806474241335

-----

query = """
SELECT u.country, o.amount
FROM orders o
JOIN users u ON o.user_id = u.id
"""

cursor.execute(query)

data = cursor.fetchall()
columns = [col[0] for col in cursor.description]

df = pd.DataFrame(data, columns=columns)

## **Nivell 2**

### **1. Representa la correlació d'algunes variables i interpreta els resultats segons les teves dades.**

### **2. Implementa un Jointplot per explorar la relació entre dues variables i interpreta els resultats segons les teves dades.**

## **Nivell 3**

### **1. Transfereix totes les visualitzacions del Nivell 1 a Power BI utilitzant scripts de Python.**

Recorda: quan carreguis els teus dataframes a Power BI, assegura't d’incloure una columna identificadora o una combinació de columnes que garanteixi la unicitat de cada registre. Per defecte, Power BI elimina duplicats i podries perdre informació.

### Pàgines web

- [How to Show All Tables in MySQL using Python?](https://www.geeksforgeeks.org/python/how-to-show-all-tables-in-mysql-using-python/)